- pycharm-professional/PKGBUILD
Update pycharm-professional to version 4.0.6
> upgpkg: pycharm-professional 4.0.6

- dmenu-xft/PKGBUILD
- dmenu-xft/lilac.py
- nvchecker.ini
- paper-gtk-theme-git/PKGBUILD
- paper-gtk-theme-git/lilac.py
- paper-icon-theme-git/PKGBUILD
- paper-icon-theme-git/lilac.py
- xflux/PKGBUILD
- xflux/lilac.py
> 添加dmenu-xft,paper-gtk-theme-git,paper-icon-theme-git,xflux

- dmenu-xft/lilac.py
- paper-gtk-theme-git/lilac.py
- paper-icon-theme-git/lilac.py
- xflux/lilac.py
特意加上了32位，结果收到邮件显示32不再支持了。。。现在重新修改了。
> remove i686 support

- nvchecker.ini
0. Run **pacman -Syy**
1. Check package use follow command **python nn.py | grep '^+'**
```python
import configparser
import os
files = os.listdir()
p = os.popen('pacman -Sl archlinuxcn | cut -d " " -f 2')
pkgs = p.read().split()
cp = configparser.ConfigParser()
cp.read('./nvchecker.ini')
nvc_pkgs = cp.sections()
for nvc_pkg in nvc_pkgs:
if nvc_pkg not in pkgs:
if nvc_pkg not in files:
check_in_git = os.popen('git log --oneline --grep "rmvpkg:.*{pkg_name}"'.format(pkg_name=nvc_pkg))
check_in_git = check_in_git.read().strip()
if check_in_git != '':
print('+ {:24} :::: {}'.format(nvc_pkg, check_in_git))
else:
print('+ {}'.format(nvc_pkg))
else:
print('* {}'.format(nvc_pkg))
```
2. Got list
+ vba-m-gtk                :::: 7658452 rmvpkg: vba-m-gtk (duplicate of [community]/vbam-gtk)
+ …
> fix issue #132: cleanup: nvchecker.ini

- kreogist-mu/lilac.py
- kvantum-kde4-colorscheme-svn/lilac.py
- nvchecker.ini
> 添加 kvantum-kde4-colorscheme-svn，kreogist-mu

- pre-commit
some checks are disabled currently.
looking for review
> improve pre-commit related with #272

- nvchecker.ini
- python-telethon/PKGBUILD
- python-telethon/lilac.py
> addpkg: python-telethon

- nvchecker.ini
- ttf-google-fonts-git/lilac.py
emm 因为不是自己名下的包，所以还是开 PR 请求确认一下。
> fix 562 update ttf-google-fonts-git upstream

- rust-nightly/PKGBUILD.tmpl
@lilydjwg 百合帮忙review下OwO
毕竟不是自己的包，还是发个PR吧。
> add rust-src-nightly

- .github/ISSUE_TEMPLATE.md
> issue template: ask more info about package requests

- .github/ISSUE_TEMPLATE.md
> Change some messages in issue template to comments

- dns-over-https/PKGBUILD
- dns-over-https/lilac.py
- nvchecker.ini
Add dns-over-https for peopel so that we can skip the annoying network problem
> Add dns-over-https

- caddy/.gitignore
- caddy/PKGBUILD
> Add gitignore

- android-ndk-beta/PKGBUILD
- android-ndk-beta/android-ndk-beta.install
- android-ndk-beta/android-ndk-beta.sh
- android-ndk-beta/lilac.py
- android-ndk/PKGBUILD
- android-ndk/lilac.py
- nvchecker.ini
See commit messages for details
> android-ndk & android-ndk-beta: improvements & additions

- yay-git/PKGBUILD
fix makepkg building error and update to commit HEAD
[aur yay-git](https://aur.archlinux.org/cgit/aur.git/commit/?h=yay-git)
> yay-git:Update to new makefile specification

- mecab-git/PKGBUILD
- mecab-git/lilac.yaml
- mecab-ipadic-neologd-git/lilac.yaml
- mecab-ipadic/PKGBUILD
- mecab-ipadic/lilac.yaml
resolve https://build.archlinuxcn.org/packages/#/mecab-ipadic-neologd-git
> resolve build mecab-ipadic-neologd-git error

- systemtap/PKGBUILD
- systemtap/systemtap.install
- systemtap/systemtap.patch
- systemtap/systemtap.sysusers
Need to change too much so lilacbot autoupdate failed.
> update systemtap to 4.0

- goldendict-qt5-git/PKGBUILD
- goldendict-qt5-git/lilac.yaml
- libeb/PKGBUILD
- libeb/lilac.yaml
官方仓库的 goldendict 不支持 EPWING 格式的辞书。
> add goldendict-qt5-git

- archlinuxcn/mirror/PKGBUILD
- archlinuxcn/mirror/lilac.yaml
mirror is an application for open source mirror site to sync files from upstream.
> mirror: add package

- archlinuxcn/bilidan-git/lilac.py
- archlinuxcn/bilidan-git/lilac.yaml
- archlinuxcn/gnome-vfs-perl/lilac.py
- archlinuxcn/gnome-vfs-perl/lilac.yaml
Replace ArchLinux CN Prefix with Extra Prefix
> Pull Request: Replace ArchLinux CN Prefix with Extra Prefix

- archlinuxcn/feeluown/PKGBUILD
- archlinuxcn/feeluown/lilac.yaml
- archlinuxcn/python-janus/PKGBUILD
- archlinuxcn/python-janus/lilac.py
- archlinuxcn/python-janus/lilac.yaml
- add python-janus
- feeluown update depends
Signed-off-by: Bruce Zhang <zttt183525594@gmail.com>
> Add python-janus: feeluown 3.x new depend

- archlinuxcn/python-torchvision/PKGBUILD
- archlinuxcn/python-torchvision/lilac.py
- archlinuxcn/python-torchvision/lilac.yaml
> python-torchvision: update lilac.yaml & lilac.py, also add quote to $var

- archlinuxcn/python-torchgan-git/PKGBUILD
- archlinuxcn/python-torchgan-git/lilac.yaml
Research Framework for easy and efficient training of GANs based on PyTorch, homepage at https://github.com/torchgan/torchgan
> add python-torchgan-git

- archlinuxcn/trace-cmd/001_do_not_isntall_cmd_when_gui.patch
- archlinuxcn/trace-cmd/002_load_from_home.patch
- archlinuxcn/trace-cmd/003_fix_plug_dir.patch
- archlinuxcn/trace-cmd/PKGBUILD
- archlinuxcn/trace-cmd/lilac.yaml
see https://aur.archlinux.org/packages/trace-cmd/#news
建议搭配 linux-lily 食用
> add pkg: trace-cmd

- archlinuxcn/paper-icon-theme/PKGBUILD
- archlinuxcn/paper-icon-theme/lilac.py
- archlinuxcn/paper-icon-theme/lilac.yaml
- AUR: https://aur.archlinux.org/packages/paper-icon-theme
- Upstream: https://github.com/snwh/paper-icon-theme
- Official: https://snwh.org/paper
Signed-off-by: Bruce Zhang <zttt183525594@gmail.com>
> Add package: paper-icon-theme

- archlinuxcn/python-tensorboardx/PKGBUILD
- archlinuxcn/python-tensorboardx/lilac.py
- archlinuxcn/python-tensorboardx/lilac.yaml
> add python-tensorboardx

- archlinuxcn/python-gluoncv-torch-git/PKGBUILD
- archlinuxcn/python-gluoncv-torch-git/lilac.py
- archlinuxcn/python-gluoncv-torch-git/lilac.yaml
PyTorch API for GluonCV Models
> add python-gluoncv-torch-git

- archlinuxcn/python-skorch/PKGBUILD
- archlinuxcn/python-skorch/lilac.py
- archlinuxcn/python-skorch/lilac.yaml
A scikit-learn compatible neural network library that wraps pytorch.
> add python-skorch

- archlinuxcn/python-augmentor/PKGBUILD
- archlinuxcn/python-augmentor/lilac.py
- archlinuxcn/python-augmentor/lilac.yaml
Image augmentation library in Python for machine learning
> add python-augmentor

- archlinuxcn/codelite-git/PKGBUILD
- archlinuxcn/codelite-git/lilac.yaml
- Add codelite-git
Signed-off-by: Bruce Zhang <zttt183525594@gmail.com>
> codelite-git: new package #1117

- archlinuxcn/python-torchfile/PKGBUILD
- archlinuxcn/python-torchfile/lilac.py
- archlinuxcn/python-torchfile/lilac.yaml
Deserialize torch-serialized objects from Python
> add python-torchfile

- archlinuxcn/python-visdom/PKGBUILD
- archlinuxcn/python-visdom/lilac.py
- archlinuxcn/python-visdom/lilac.yaml
A flexible tool for creating, organizing, and sharing visualizations of live, rich data. Supports Torch and Numpy.
> add python-visdom

- archlinuxcn/lxqt-git-meta/PKGBUILD
- archlinuxcn/lxqt-git-meta/lilac.yaml
Requested in https://github.com/archlinuxcn/repo/issues/1141
/cc @ykelvis
> lxqt-git-meta: new package

- archlinuxcn/python-pydicom/PKGBUILD
- archlinuxcn/python-pydicom/lilac.py
- archlinuxcn/python-pydicom/lilac.yaml
Read, modify and write DICOM files with python code
> add python-pydicom

- archlinuxcn/charls/PKGBUILD
- archlinuxcn/charls/lilac.py
- archlinuxcn/charls/lilac.yaml
a C++ JPEG-LS library implementation
> add charls

- archlinuxcn/python-medpy/PKGBUILD
- archlinuxcn/python-medpy/lilac.py
- archlinuxcn/python-medpy/lilac.yaml
Medical image processing in Python
> add python-medpy

- archlinuxcn/insight-toolkit/PKGBUILD
- archlinuxcn/insight-toolkit/lilac.py
- archlinuxcn/insight-toolkit/lilac.yaml
Cross-platform system that provides developers with an extensive suite of software tools for image analysis
> add insight-toolkit

- archlinuxcn/systemtap/PKGBUILD
- archlinuxcn/systemtap/lilac.yaml
- archlinuxcn/systemtap/systemtap.patch
fix: #1099 
works on kernel 5.0.13-arch1(with debuginfo)
preview: /home/sasasu/repo/archlinuxcn/systemtap/systemtap-4.1-1-x86_64.pkg.tar.xz
> updatepkg: systemtap

- archlinuxcn/python-itk/PKGBUILD
- archlinuxcn/python-itk/lilac.py
- archlinuxcn/python-itk/lilac.yaml
An open-source toolkit for multidimensional image analysis. This package include itk-core, itk-filtering, itk-io, itk-numerics, itk-registration, and itk-segmentation module.
> add python-itk

- archlinuxcn/itk-snap-bin/PKGBUILD
- archlinuxcn/itk-snap-bin/lilac.py
- archlinuxcn/itk-snap-bin/lilac.yaml
A software application used to segment structures in 3D medical images
> add itk-snap-bin

- archlinuxcn/python-onnx/PKGBUILD
- archlinuxcn/python-onnx/lilac.py
- archlinuxcn/python-onnx/lilac.yaml
- archlinuxcn/python-onnx/no-typing.patch
> python-onnx: run tests

- archlinuxcn/electron-netease-cloud-music/PKGBUILD
https://github.com/Rocket1184/electron-netease-cloud-music/commit/4e0d7b0e2b3195650bd1ec5b5230330ae1be1163
@a-wing
> update electron-netease-cloud-music: use svg icon

- archlinuxcn/hikarujs/PKGBUILD
- archlinuxcn/hikarujs/lilac.yaml
Added my own static site generator Hikaru from AUR (also maintained by myself).
> Added hikarujs

- archlinuxcn/himawaripy-git/PKGBUILD
- archlinuxcn/himawaripy-git/himawaripy.install
- archlinuxcn/himawaripy-git/lilac.yaml
> Set near-realtime picture of Earth as your desktop background http://labs.boramalper.org/himawaripy
> add himawaripy-git

- archlinuxcn/ocserv/PKGBUILD
Update ocserv 0.12.4 to 0.12.5
> Update ocserv 0.12.4 to 0.12.5

- archlinuxcn/ttyplot/PKGBUILD
- archlinuxcn/ttyplot/lilac.yaml
A realtime plotting utility for terminal.
> add package: ttyplot

- archlinuxcn/motrix-git/PKGBUILD
- archlinuxcn/motrix-git/lilac.py
- archlinuxcn/motrix-git/lilac.yaml
A full-featured download manager.
> add motrix-git

- archlinuxcn/github-cli/PKGBUILD
- archlinuxcn/github-cli/lilac.yaml
The GitHub CLI
https://github.com/cli/cli
> addpkg: github-cli

- archlinuxcn/qv2ray-dev-git/PKGBUILD
arch users don't need this. we've got pacman!
---
cc @axionl
> qv2ray-dev-git: disable builtin update checker

- archlinuxcn/qv2ray/PKGBUILD
same change as qv2ray-dev-git in cbc30e0ac49d1b1c709808b1eed6fb42933a505f
> qv2ray: updating dependencies

- archlinuxcn/v2ray-desktop/PKGBUILD
- archlinuxcn/v2ray-desktop/lilac.py
- archlinuxcn/v2ray-desktop/lilac.yaml
Create package for V2Ray-Desktop.
AUR: https://aur.archlinux.org/packages/v2ray-desktop/
GitHub: https://github.com/Dr-Incognito/V2Ray-Desktop
> addpkg: v2ray-desktop

- archlinuxcn/hplip-plugin/lilac.py
- archlinuxcn/hplip-plugin/lilac.yaml
> hplip-plugin: update on hplip from archpkg

- archlinuxcn/hplip-plugin/lilac.py
- archlinuxcn/hplip-plugin/lilac.yaml
> hplip-plugin: fix lilac.yaml

- archlinuxcn/optimus-manager-qt/PKGBUILD
> [optimus-manager-qt] fix empty package for kde

- archlinuxcn/python-tifffile/PKGBUILD
- archlinuxcn/python-tifffile/lilac.py
- archlinuxcn/python-tifffile/lilac.yaml
> addpkg: python-tifffile

- archlinuxcn/python-scikit-image/PKGBUILD
- archlinuxcn/python-scikit-image/lilac.py
- archlinuxcn/python-scikit-image/lilac.yaml
1. rewrite PKGBUILD
2. update depends
ref #1648
> python-scikit-image: update PKGBUILD

- archlinuxcn/naiveproxy-git/PKGBUILD
- archlinuxcn/naiveproxy-git/lilac.yaml
> NOTE: Please **SQUASH** and **DELETE SOURCE BRANCH** when merging.
> addpkg: naiveproxy-git

- archlinuxcn/libime-git/PKGBUILD
> libime-git: provides libime

- pre-commit
A sample failure: https://travis-ci.org/github/yan12125/repo/builds/690525748
> pre-commit: deny embedded repos (submodules)

- archlinuxcn/fgit-go/PKGBUILD
@DuckSoft Hi there, plz review.
> fgit-go: move command to fgit

- .github/ISSUE_TEMPLATE/10-request.md
Can't stand the bad formatting in all the package requests anymore = = .....
> Fix package request template formatting

- archlinuxcn/fcitx5-pinyin-zhwiki-rime/PKGBUILD
- archlinuxcn/fcitx5-pinyin-zhwiki-rime/lilac.yaml
Use the PKGBUILD in AUR maintained by me.
> addpkg: fcitx5-pinyin-zhwiki-rime

- .github/workflows/test.yml
- pre-commit
Add Github Actions support, doing the same job as travis does, but with a better GitHub integrated support.
> CI: Add GitHub Actions

- archlinuxcn/v2raya/PKGBUILD
add param --check-files of yarn to verify file tree of packages for consistency #1950
> Update PKGBUILD of v2rayA

- archlinuxcn/libpdfium-nojs/lilac.py
- archlinuxcn/libpdfium-nojs/lilac.yaml
> libpdfium-nojs: fix auto-updating with lilac

- archlinuxcn/pacroller-git/PKGBUILD
- archlinuxcn/pacroller-git/lilac.yaml
- archlinuxcn/pacroller/PKGBUILD
- archlinuxcn/pacroller/lilac.yaml
> addpkg: pacroller and pacroller-git

- archlinuxcn/transmission-web-control-git/PKGBUILD
- archlinuxcn/transmission-web-control-git/lilac.py
- archlinuxcn/transmission-web-control-git/lilac.yaml
- archlinuxcn/transmission-web-control-git/transmission-web-control-git.hook
- archlinuxcn/transmission-web-control-git/transmission-web-control-git.install
这个和我在 #1979 提供的打包不一样，使用了一个tricky的方法覆盖了`transmission`自带的index.html文件。这样做可以很方便地原地刷新来更换webui截面，之前需要导出环境变量、重启`transmission`。但是不知道这样更换其它包的文件合不合适？
第一次把自己打的包提PR，有错误的话麻烦更正 :smile:
> Add transmission web control git

- archlinuxcn/ibus-libzhuyin/PKGBUILD
I don't know why lilacbot didn't update this
> update for package ibus-libzhuyin

- archlinuxcn/llvm-git/PKGBUILD
> That shouldn't be there

- archlinuxcn/sendanywhere/LICENSE
- archlinuxcn/sendanywhere/PKGBUILD
- archlinuxcn/sendanywhere/lilac.yaml
Send Anywhere is a multi-platform file sharing service where users can directly share digital content in real time.
package from AUR.
> addpkg: sendanywhere

- archlinuxcn/qemu-git/lilac.yaml
this pull request fixes https://github.com/archlinuxcn/repo/issues/2163.
> qemu-git: trigger rebuild

- archlinuxcn/timeshift/lilac.py
Fixes https://github.com/archlinuxcn/repo/issues/2167
> timeshift: add depends

- archlinuxcn/sqlmap-git/PKGBUILD
- archlinuxcn/sqlmap-git/lilac.yaml
also adds ducksoft as co-maintainer
fixes https://github.com/archlinuxcn/repo/issues/1931
> sqlmap-git: use python3

- archlinuxcn/shadowsocks-rust-git/PKGBUILD
- archlinuxcn/shadowsocks-rust-git/lilac.py
- archlinuxcn/shadowsocks-rust-git/lilac.yaml
- archlinuxcn/shadowsocks-rust-git/shadowsocks-rust-server@.service
- archlinuxcn/shadowsocks-rust-git/shadowsocks-rust@.service
> addpkg: shadowsocks-rust-git

- archlinuxcn/lean-community/lilac.yaml
- archlinuxcn/python-mathlibtools/lilac.yaml
> harden aur_pre_build for lean related packages

- archlinuxcn/llvm-git/PKGBUILD
> fixing manfiles also adding lua to lldb

- archlinuxcn/mirror/lilac.yaml
> Add maintainer with aur_pre_build in lilac.yaml

- archlinuxcn/authy/lilac.yaml
- archlinuxcn/cocomusic/lilac.yaml
- archlinuxcn/crow-translate/lilac.yaml
- archlinuxcn/desktop-naotu/lilac.py
- archlinuxcn/electron4-bin/lilac.yaml
- archlinuxcn/electron8-bin/lilac.yaml
- archlinuxcn/protontricks/lilac.yaml
- archlinuxcn/python-m3u8/lilac.yaml
- archlinuxcn/python-vdf/lilac.yaml
- archlinuxcn/systemd-kcm/lilac.yaml
Harden aur_pre_build by brucezhang1993
> Harden aur_pre_build by brucezhang1993 (#2228)

- archlinuxcn/qv2ray/PKGBUILD
- archlinuxcn/qv2ray/missing-header-zxing-cpp.patch
Fixes https://github.com/archlinuxcn/repo/issues/2312.
> fix(qv2ray): add patch for missing header

- archlinuxcn/python-onnx/PKGBUILD
- archlinuxcn/python-onnx/lilac.yaml
mxnet is provided by mxnet-git in [archlinuxcn], and the latter often
fails. In such cases, packages depending on python-onnx also fail with
"xxx 出现依赖问题".
ONNX does not actually import any of those deep learning frameworks:
```
$ rg -g '!*.onnx' '\b(tensorflow|torch|mxnet)\b'
docs/DefineDifferentiability.md
23:The first way is to show that the considered operator's backward operation exists in an existing framework such as Pytorch or Tensorflow. In this case, the author should provide a runnable python script which computes the backward pass of the considered operator. The author should also point out how to map the Pytorch or Tensor code to ONNX format (for example, the author can call `torch.onnx.export` to save an ONNX model). The following script shows the differentiability of ONNX …
```
> python-onnx: remove unneeded dependencies

- archlinuxcn/llvm-git/PKGBUILD
> bunch of new scripts were added so i'm just going to move everything

- archlinuxcn/elan-lean/lilac.py
- archlinuxcn/elan-lean/lilac.yaml
> elan-lean: fix pre/post_build

- archlinuxcn/ryujinx-git/PKGBUILD
> ryujinx-git: Add categories

- archlinuxcn/vim-youcompleteme-git/lilac.yaml
> add python update_on for vim-youcompleteme-git

- archlinuxcn/nordic-theme/PKGBUILD
- archlinuxcn/nordic-theme/lilac.py
- archlinuxcn/nordic-theme/lilac.yaml
change auto update from aur to github, and update theme package version from 2.0.0 to 2.1.0
> pkg:nordic-theme: change auto update from aur to github

- archlinuxcn/collectd/PKGBUILD
- archlinuxcn/collectd/lilac.yaml
> [collectd] trigger rebuild and add rebuild trigger for Python updates

- archlinuxcn/rust-nightly/PKGBUILD.tmpl
- archlinuxcn/rust-nightly/lilac.py
> addpkg: rust-miri-nightly

- archlinuxcn/llvm-git/PKGBUILD
a thing was missing in the folder stuff, because i guess it was deleted
> llvm-git: fixing the missing folder

- archlinuxcn/electron-netease-cloud-music/PKGBUILD
- archlinuxcn/electron-netease-cloud-music/electron-netease-cloud-music.sh
> fixpkg: electron-netease-cloud-music

- archlinuxcn/llvm-git/PKGBUILD
- archlinuxcn/mesa-git/PKGBUILD
I'm also adding more files in clang-git/usr/bin fixing conflicts in pacman
Next, i'm going to push mesa fixes/updates
> fix: (llvm-git, lib32-llvm-git) the reasons why they can't install 

- archlinuxcn/electron11-bin/PKGBUILD
- archlinuxcn/electron11-bin/lilac.yaml
We need electron11 for motrix, see https://github.com/archlinuxcn/repo/issues/2911
> addpkg: electron11-bin

- archlinuxcn/clash-meta/PKGBUILD
- archlinuxcn/clash-meta/clash-meta.service
- archlinuxcn/clash-meta/clash-meta.sysusers
- archlinuxcn/clash-meta/clash-meta.tmpfiles
- archlinuxcn/clash-meta/clash-meta@.service
- archlinuxcn/clash-meta/config.yaml
- archlinuxcn/clash-meta/lilac.yaml
- archlinuxcn/clash-verge/PKGBUILD
- archlinuxcn/clash-verge/clash-verge.desktop
- archlinuxcn/clash-verge/lilac.yaml
- archlinuxcn/quickjs/PKGBUILD
- archlinuxcn/quickjs/lilac.yaml
This is a PKGBUILD that build clash-verge from source
see https://github.com/archlinuxcn/repo/issues/2885#issuecomment-1252484229
> Add clash-verge

- archlinuxcn/oh-my-posh-bin/PKGBUILD
- archlinuxcn/oh-my-posh-bin/lilac.yaml
一个很好用的终端美化工具，界面十分华丽
https://ohmyposh.dev/
> oh-my-posh-bin: new package

- archlinuxcn/oh-my-posh/PKGBUILD
- archlinuxcn/oh-my-posh/lilac.yaml
一个很好用的终端美化工具，界面十分华丽
https://ohmyposh.dev/
> oh-my-posh: add new package

- archlinuxcn/llvm-git/PKGBUILD
Getting the docs installed on my local machine, making the python3 stuff work, and other general changes
> (llvm-git) fixing build and installation

- archlinuxcn/lib32-llvm-git/PKGBUILD
> (lib32-llvm-git) removing python2, and other general fixes

- archlinuxcn/mesa-git/PKGBUILD
undo clang change
undo clang change
llvm is a harsh mistress
> (mesa-git) fix build and other misc changes

- archlinuxcn/opengnb-git/PKGBUILD
- archlinuxcn/opengnb-git/lilac.yaml
- 修复 opengnb-git 编译失败的问题
- 使用 Arch 系统 miniupnpc 包
- 取消 ghproxy.com 代理，改为直连
> Fixed opengnb-git

- archlinuxcn/miktex/lilac.yaml
Following https://github.com/archlinuxcn/repo/issues/3102#issuecomment-1374843462, closes https://github.com/archlinuxcn/repo/issues/3102
> Add update_on alias: icu to `miktex`

- archlinuxcn/oh-my-posh/PKGBUILD
Upstream have renamed the mod, rename the file to install.
> oh-my-posh: fix the build process

- archlinuxcn/libgbinder/PKGBUILD
- archlinuxcn/libgbinder/lilac.yaml
- archlinuxcn/libglibutil/PKGBUILD
- archlinuxcn/libglibutil/lilac.yaml
- archlinuxcn/python-gbinder/PKGBUILD
- archlinuxcn/python-gbinder/lilac.yaml
- archlinuxcn/waydroid/PKGBUILD
- archlinuxcn/waydroid/lilac.yaml
[waydroid](https://github.com/waydroid/waydroid), 一个在 wayland 环境下运行的安卓容器
> Add waydroid

- archlinuxcn/kmonad-git/PKGBUILD
- archlinuxcn/kmonad-git/lilac.yaml
add kmonad-git, [upstream](https://github.com/kmonad/kmonad), PKGBUILD comes from [AUR](https://aur.archlinux.org/packages/kmonad-git).
close #3045
> add kmonad-git

- archlinuxcn/llvm-git/PKGBUILD
> (llvm-git) fix llvmver and adding depends

- archlinuxcn/emacs-git/lilac.py
> emacs-git: enable tree-sitter

- archlinuxcn/prismlauncher-git/PKGBUILD
just shamelessly copied from [prismlauncher-git<sup>AUR</sup>](https://aur.archlinux.org/packages/prismlauncher-git)
> prismlauncher-git: fix depends

- archlinuxcn/64gram-desktop/lilac.yaml
update info according to https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=64gram-desktop
> update 64gram info

- archlinuxcn/nordic-theme/PKGBUILD
All other nordic-* packages merged into this one. 
except nordic-polar-theme nordic-kde.
> nordic-* packages merge, except nordic-polar/kde

- archlinuxcn/elan-lean/lilac.py
- archlinuxcn/elan-lean/lilac.yaml
Migrate from lilac.py to lilac.yaml
> elan-lean: update lilac.yaml

- archlinuxcn/elan-lean/PKGBUILD
This commit should fix package build errors.
> elan-lean: fix lto issue

- archlinuxcn/xpadneo-dkms/PKGBUILD
- archlinuxcn/xpadneo-dkms/drop-etc-files.patch
- archlinuxcn/xpadneo-dkms/lilac.yaml
- archlinuxcn/xpadneo-dkms/rename-marker.patch
the xbox wireless controller driver that works for me
> xpadneo-dkms: add new package to repo

- archlinuxcn/telegram-desktop-megumifox/PKGBUILD
- archlinuxcn/telegram-desktop-megumifox/lilac.yaml
See https://bugs.archlinux.org/task/78330 and https://github.com/archlinux/svntogit-community/commit/6c60c30835d4a68f5b36c7447b55ae098f710b56
> telegram-desktop-megumifox: build with openssl 3

- archlinuxcn/cpu-x/PKGBUILD
- archlinuxcn/cpu-x/lilac.yaml
> package:cpu-x: bump cpu-x from 4.5.0 to 4.5.3

- archlinuxcn/llvm-git/PKGBUILD
Also adding Spirv-llvm-translator-git
> llvm-git: Fix Build

- archlinuxcn/sunshine/PKGBUILD
- archlinuxcn/sunshine/lilac.yaml
- archlinuxcn/sunshine/sunshine.install
game stream host for Moonlight
> add package: sunshine

- archlinuxcn/refind-theme-dracula/PKGBUILD
- archlinuxcn/refind-theme-dracula/lilac.yaml
- archlinuxcn/refind-theme-dracula/refind-theme-dracula.install
package a beautiful theme for  UEFI bootloader  -- refind
upstream source: [github - refind-theme-dracula](https://github.com/rassweiler/refind-theme-dracula)
demo screenshot:
> add new package: refind-theme-dracula

- .github/workflows/test.yml
- Update actions/checkout from v2 to v4
- Update actions/setup-python from v2 to v4
- Update python version from 3.8 to 3.11
> chore(workflows/test.yml): update actions and python version

- archlinuxcn/qt5-base-24h/lilac.py
- archlinuxcn/qt5-base-24h/lilac.yaml
- archlinuxcn/qt5-base-24hms/lilac.py
- archlinuxcn/qt5-base-24hms/lilac.yaml
- archlinuxcn/qt6-base-24h/lilac.py
- archlinuxcn/qt6-base-24h/lilac.yaml
- archlinuxcn/qt6-base-24hms/lilac.py
- archlinuxcn/qt6-base-24hms/lilac.yaml
libicudata.so is not a direct dependency, use libicui18n.so instead
> qt{5,6}-base-24h{,ms} : Fix/add soname depends on icu

- archlinuxcn/fcitx5-configtool-git/PKGBUILD
https://github.com/archlinuxcn/repo/issues/3507
>  fcitx5-configtool-git: fix deps

- archlinuxcn/nheko-git/PKGBUILD
- archlinuxcn/nheko-git/lilac.yaml
> nheko-git: Fix build after qt6 port

- archlinuxcn/nheko-git/PKGBUILD
> nheko-git: Fix build

- archlinuxcn/candy/PKGBUILD
- archlinuxcn/candy/lilac.yaml
Another VPN that supports peer-to-peer connections.
> candy: add package

- archlinuxcn/cambalache/PKGBUILD
- archlinuxcn/cambalache/lilac.yaml
package: cambalache
source: [gnome](https://gitlab.gnome.org/jpu/cambalache)
form: AUR cambalache
test: extra-x86_64-build PASSED
glade的后继者，支持gtk4!!!!
> cambalache: Addpkg

- archlinuxcn/ttfautohint/PKGBUILD
- archlinuxcn/ttfautohint/lilac.yaml
https://github.com/alerque/aur/pull/72
> fix(ttfautohint): fix errors reported by namcap

- archlinuxcn/64gram-desktop/lilac.yaml
> provided: libvpx.so

- archlinuxcn/naiveproxy/lilac.py
- archlinuxcn/naiveproxy/lilac.yaml
use  lilac to automatically update aur repo
> naiveproxy: add lilac.py

- archlinuxcn/doukutsu-save-editor-git/PKGBUILD
- archlinuxcn/doukutsu-save-editor-git/lilac.yaml
> Add doukutsu-save-editor-git

- archlinuxcn/video-trimmer/PKGBUILD
- archlinuxcn/video-trimmer/lilac.yaml
light weight video cutter written in Rust, included in gnome-circles
carry from [AUR](https://aur.archlinux.org/packages/video-trimmer)
> Add video-trimmer: a light video cutter in Rust

- archlinuxcn/librime-sbxlm-git/002-fix-glog-0.7.patch
- archlinuxcn/librime-sbxlm-git/PKGBUILD
- archlinuxcn/librime-sbxlm/001-fix-warning.patch
- archlinuxcn/librime-sbxlm/002-fix-glog-0.7.patch
- archlinuxcn/librime-sbxlm/PKGBUILD
reference: https://gitlab.archlinux.org/archlinux/packaging/packages/librime/-/commit/38bb3b1eb10e81185fb3057a65c4c9fd34386ed5
> librime-sbxlm: fix build with glog 0.7

- archlinuxcn/spirv-headers-git/lilac.yaml
the aur has a strange pkgver going on
> fix (spirv-headers-git): delete the updates from aur thing

- archlinuxcn/rime-ice-git/PKGBUILD
- archlinuxcn/rime-ice-git/lilac.yaml
第一次给 CN 提交包，不知道有没有问题，辛苦 review 的童鞋了。
> rime-ice-git: add package

- archlinuxcn/llvm-git/PKGBUILD
it wasn't building and now it's building.  I also moved things to the source
> fix(llvm-git): Fix the build and pkgver

- archlinuxcn/amberol/lilac.yaml
- archlinuxcn/cambalache/lilac.yaml
- archlinuxcn/clash-verge/lilac.yaml
- archlinuxcn/video-trimmer/lilac.yaml
Add email to lilac:
- clash-verge
- amberol
- cambalache
- video-trimmer
> Add email to lilac

- archlinuxcn/lib32-llvm-git/PKGBUILD
see the other pull request as well
> fix (lib32-llvm-git): fix pkgver and other stuff

- archlinuxcn/64gram-desktop/PKGBUILD
> https://github.com/archlinuxcn/repo/pull/3746/files

- archlinuxcn/sing-geoip/PKGBUILD
- archlinuxcn/sing-geosite/PKGBUILD
feat: sing-geoip, sing-geosite *-cn.db
> fix: sing-geoip, sing-geosite checksum

- archlinuxcn/sing-box/lilac.yaml
RT，我是 AUR [sing-box](https://aur.archlinux.org/packages/sing-box) 的维护者，已将 `lilac` 加入共同维护者
> feat(sing-box): auto update AUR repo

- archlinuxcn/yazi-git/PKGBUILD
https://github.com/sxyazi/yazi/issues/914
> yazi-git: Install new standalone binary `ya`

- archlinuxcn/spirv-tools-git/PKGBUILD
- archlinuxcn/spirv-tools-git/lilac.yaml
it asks for spirv-tools in cmake checks, it should probably also be asking for the features or updates in spirv-tools-git
> feat(spirv-tools-git): adding dependency for spirv-llvm-translator

- archlinuxcn/lib32-llvm-git/PKGBUILD
- archlinuxcn/lib32-llvm-git/lilac.yaml
i saw that the build was failing and i fixed the reason why the build was failing
> fix(lib32-llvm-git): fixing the build by adding the changes

- archlinuxcn/lib32-spirv-tools-git/lilac.yaml
making sure the package builds
> fix(lib32-spirv-tools-git): adding spirv-tools-git

- archlinuxcn/mesa-git/PKGBUILD
- archlinuxcn/mesa-git/lilac.yaml
it has bug fixes, it has packaging changes it has so many changes
> feat(mesa-git): a lot of updates

- archlinuxcn/ooniprobe-cli/PKGBUILD
- archlinuxcn/ooniprobe-cli/lilac.py
- archlinuxcn/ooniprobe-cli/lilac.yaml
> addpkg: ooniprobe-cli

- archlinuxcn/sing-box-alpha/PKGBUILD
- archlinuxcn/sing-box-alpha/lilac.yaml
- archlinuxcn/sing-box-alpha/sing-box.rules
> sing-box-alpha: add package

- archlinuxcn/clash-verge/PKGBUILD
tested in local, This time will be OKay, @Integral-Tech
> clash-verge: fix PKGBUILD

- archlinuxcn/ventoy/PKGBUILD
- archlinuxcn/ventoy/lilac.yaml
- archlinuxcn/ventoy/wimboot-binutils-2.42-fix.patch
copy from AUR， tested in build.machine in extra-x86_64-build
> ventoy: add pkg

- archlinuxcn/meta-rules-dat/PKGBUILD
- archlinuxcn/meta-rules-dat/lilac.yaml
adopt pkg from https://github.com/archlinuxcn/repo/issues/3897
> meta-rules-dat: adopt pkg

- archlinuxcn/kwin-decoration-sierra-breeze-enhanced/PKGBUILD
- archlinuxcn/kwin-decoration-sierra-breeze-enhanced/lilac.yaml
[kwin-decoration-sierra-breeze-enhanced](https://github.com/kupiqu/SierraBreezeEnhanced): Originally a fork of BreezeEnhanced to make it (arguably) more minimalistic and informative
> addpkg: kwin-decoration-sierra-breeze-enhanced

- archlinuxcn/serenity/lilac.yaml
https://github.com/archlinuxcn/repo/pull/3939#issuecomment-2252902071
> serenity: update nvchecker config

- archlinuxcn/goldendict-ng-git/lilac.yaml
fix #4020 
same as https://github.com/archlinuxcn/repo/commit/40e68d2d166b8e3fe5bd280154874c794acdf732
> goldendict-ng-git: add update_on libfmt

- archlinuxcn/naiveproxy/PKGBUILD
- archlinuxcn/naiveproxy/lilac.py
- archlinuxcn/naiveproxy/lilac.yaml
> fix naiveproxy build

- archlinuxcn/caddy-bgme/PKGBUILD
- archlinuxcn/caddy-bgme/lilac.yaml
fix(caddy-bgme):  remove duplicated update_on from lilac.yaml
> fix(caddy-bgme):  remove duplicated update_on from lilac.yaml

- archlinuxcn/dida/lilac.yaml
> dida: add update source based on the official website download link

- archlinuxcn/looking-glass-rc/PKGBUILD
- archlinuxcn/looking-glass-rc/lilac.yaml
> looking-glass-rc: set OPTIMIZE_FOR_NATIVE to x86-64-v2

- archlinuxcn/ecapture/PKGBUILD
- archlinuxcn/ecapture/lilac.yaml
> add ecapture

- archlinuxcn/ecapture/lilac.yaml
> ecapture: force rebuild

- archlinuxcn/ruyi/lilac.yaml
`ruyi` need rebuild when `python` updated
> ruyi: add alias python

- archlinuxcn/wiliwili/PKGBUILD
- archlinuxcn/wiliwili/lilac.yaml
顺带修正了 `wiliwili-debug` 中缺少符号的问题。
> wiliwili: use system qrcodegen and fmt

- archlinuxcn/oh-my-posh/PKGBUILD
* Upstream has dropped completion so we also need to remove related code here
> oh-my-posh: sync changes from AUR to fix build

- archlinuxcn/qucs-s-git/PKGBUILD
- archlinuxcn/qucs-s-git/lilac.yaml
Qucs-S provides GUI for different circuit simulation kernels.
> Add qucs-s-git

- archlinuxcn/wiliwili/lilac.yaml
> wiliwili: fix update sources

- archlinuxcn/wiliwili/lilac.yaml
这下应该彻底修好了吧（
因为我的不专业导致产生了一些重复的 PR / Commit，在这里说一句不好意思。
> wiliwili: fix regex for updated sources

- archlinuxcn/rime-sbxlm/PKGBUILD
> rime-sbxlm: update release url and license url

- archlinuxcn/waydroid-git/PKGBUILD
- archlinuxcn/waydroid/PKGBUILD
> waydroid & waydroid-git: switch to system-provided python package

- archlinuxcn/keypunch-git/lilac.yaml
The lilac.yaml has an error,need to fix
> fix lilac.yaml of keypunch-git
