archlinuxcn/repo

.gitignore
.travis.yml

As discussed in #272 and #273 , we can run a travis-ci after the commit is made.
This will hopefully enforce checking and find problems earlier.
Also added shellcheck all PKGBUILDs and ignore its return value. The checking log maybe helpful.

run ./pre-commit and shellcheck on travis

---

rust-nightly/lilac.py

[std: Add a new wasm32-unknown-unknown target](https://github.com/rust-lang/rust/pull/45905)
[rustbuild: Enable WebAssembly backend by default](https://github.com/rust-lang/rust/pull/46115)
I'm not sure whether this back end has additional dependencies, so just left it empty.

add rust-nightly-wasm32-unknown-unknown

---

websocketd/lilac.py

Fix websocketd lilac.py  _G.newver.lstrip('v')

---

pre-commit

This change on pre-commit hook tries to check the index tree (files already added by `git add`) instead of the working tree. So that it will not see the ignored/removed files (as they not being in the index tree), and will detect mistakes like forgetting to add modified nvchecker.ini.
The down side: `git commit` will take more than 5 secs on my SSD machine, because all the `popen("git", ...)` costs. I already tried `lru_cache` to save some time. It was more than 10s before using lru_cache.
Should we use this new hook or stick to the old one (which is more quicker) ?

pre-commit check index tree instead of working tree

---

ccls-git/lilac.py
nvchecker.ini

ccls-git: track github instead of aur

---

nvchecker.ini

This package was tracking local pacman database. If local databases are
not up-to-date, this package will not be updated either. This is the
case on build.archlinuxcn.org as of now.
Closes: https://github.com/archlinuxcn/repo/issues/918

virtualbox-ext-oracle: make it follow AUR

---

ttf-migu/PKGBUILD
ttf-migu/lilac.yaml

- Migu
M+ 和 IPAゴシック 合成的字体，非常易读。
https://mix-mplus-ipa.osdn.jp/migu/
~- Ricty~
~Inconsolata 和 Migu 1M 合成的编程用字体。~
~https://www.rs.tus.ac.jp/yyusa/ricty.html~

fonts: add ttf-migu

---

beignet-git/lilac.yaml
devtools-cn-git/lilac.yaml
emacs-julia-mode-git/lilac.yaml
emacs-llvm-mode-git/lilac.yaml
emacs-markdown-mode-git/lilac.yaml
julia-pkg-scripts/lilac.yaml
libunwind-git/lilac.yaml
libutf8proc-git/lilac.yaml
oce-git/lilac.yaml
openblas-lapack-git/lilac.yaml
openlibm-git/lilac.yaml
openspecfun-git/lilac.yaml
rr-git/lilac.yaml
scribus-svn/lilac.yaml
spice-vdagent-git/lilac.yaml
virtualbox-svn/lilac.yaml

Most likely they are victims of a nvchecker2yaml bug.

tree-wide: fix incorrect vcs specs in update_on

---

archlinuxcn/systemtap/PKGBUILD
archlinuxcn/systemtap/lilac.yaml

Since readline is upgraded to 8.0.0, libreadline.so.7 does not exist now. So systemtap needs to be rebuilt.
However my question is, if a package depends on readline, and if readline upgrades, will other packages depend on it be rebuilt automatically?

Add missed depends of systemtap: readline, nspr

---

archlinuxcn/amarok/PKGBUILD
archlinuxcn/amarok/amarok.patch

1. 由于mariadb的mysql_config不再提供--libmysqld-libs参数，按照旧的FindMySQL.cmake导致cmake会去链接libmysqlclient，而不是libmysqld，这样的话会导致amarok启动时出现mysql embedded server启动失败的错误 ，进而无法正常使用该功能。
2. 如果是因为[这里](https://www.libssh.org/archive/libssh/2018-08/0000032.html)提到的问题，导致需要依赖libssh-gnutls。经过测试发现目前已经没有这个问题了，依赖libssh也能正常工作。

amarok: 修复启动时提示mysql嵌入式服务器启动失败，更改依赖libssh-gnutls为libssh

---

archlinuxcn/litecli/lilac.yaml

[fixed] litecli: use extra-x86_64 instead of archlinuxcn-x86_64

---

archlinuxcn/kicad-i18n-git/PKGBUILD
archlinuxcn/kicad-i18n-git/lilac.py
archlinuxcn/kicad-i18n-git/lilac.yaml

Add package `kicad-i18n-git` : Translations for KiCad source code.
Added lilac as Co-Maintainer of [kicad-i18n-git on AUR](https://aur.archlinux.org/packages/kicad-i18n-git).

add package: kicad-i18n-git

---

archlinuxcn/jdownloader2/jdownloader

Both JDownloader and jdownloader are in the repo, which confuses case-insensitive file systems like APFS. (I sync the archlinuxcn repo across all my devices, so this repo appears on both EXT4 and APFS.)

jdownloader2: remove an unused file

---

lilac-yaml-schema.yaml

No longer true after https://github.com/archlinuxcn/lilac/pull/114.

Sync lilac-yaml-schema.yaml from archlinuxcn/lilac 

---

archlinuxcn/vidalia/lilac.yaml

Closes: #1154 - this is the only remaining package in need of an action
PS: I didn't test this change myself.

vidalia: declare qt4 dependency

---

archlinuxcn/code-transparent/PKGBUILD
archlinuxcn/code-transparent/code-liveshare.diff
archlinuxcn/code-transparent/code-transparent.install
archlinuxcn/code-transparent/code.js
archlinuxcn/code-transparent/code.sh
archlinuxcn/code-transparent/enable-proposed-apis.diff
archlinuxcn/code-transparent/lilac.yaml
archlinuxcn/code-transparent/product_json.diff
archlinuxcn/code-transparent/transparent.diff

这个包是我维护的同名 AUR 包（增加了透明支持的 VS Code），它是基于 Arch 官方源的 code 包基础上加了 patch，所以理论上检查 out of date 是根据 archpkg: code 来， rebuild 是根据 aur 来。
看了 https://archlinuxcn.github.io/lilac/ 描述第一个是用于更新检查的，但是头一次这么用希望确认一下没有搞错（

addpkg: code-transparent

---

archlinuxcn/systemtap/PKGBUILD

https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/glibc
glibc provides sdt.h and sdt-config.h now.

fix file conflict with glibc 2.30-2

---

archlinuxcn/alttab-git/PKGBUILD
archlinuxcn/alttab-git/lilac.yaml

配合 i3wm 用还是挺不错的。
我目前用的一个配置：
`exec_always alttab -mk Super_L -fg "#d58681" -bg "#4a4a4a" -frame "#eb564d" -t 256x384 -i 256x256 -d 1`

add alttab-git

---

archlinuxcn/arm-linux-gnueabihf-binutils/lilac.yaml
archlinuxcn/arm-linux-gnueabihf-glibc/lilac.yaml
archlinuxcn/arm-linux-gnueabihf-linux-api-headers/lilac.yaml
archlinuxcn/auracle-git/lilac.yaml
archlinuxcn/coccinelle/lilac.yaml
archlinuxcn/freecad/lilac.yaml
archlinuxcn/gottet/lilac.yaml
archlinuxcn/gradio/lilac.yaml
archlinuxcn/hplip-plugin/lilac.yaml
archlinuxcn/ispin/lilac.yaml
archlinuxcn/lib32-gdbm/lilac.yaml
archlinuxcn/lib32-tk/lilac.yaml
archlinuxcn/libgit2-julia/lilac.yaml
archlinuxcn/llvm-julia/lilac.yaml
archlinuxcn/llvm-svn/lilac.yaml
archlinuxcn/lumina-desktop/lilac.yaml
archlinuxcn/nodejs-tiddlywiki/lilac.yaml
archlinuxcn/numix-circle-icon-theme-git/lilac.yaml
archlinuxcn/numix-icon-theme-git/lilac.yaml
archlinuxcn/openvdb3/lilac.yaml
archlinuxcn/spin/lilac.yaml
archlinuxcn/stapler-git/lilac.yaml
archlinuxcn/supertux-git/lilac.yaml
archlinuxcn/uksmtools/lilac.yaml
archlinuxcn/xfce4-mpc-plugin-update/lilac.yaml
archlinuxcn/xrdp/lilac.yaml
archlinuxcn/youtube-dl-git/lilac.yaml

Maintainers are determined by last packagers and git commits.
Closes https://github.com/archlinuxcn/repo/issues/1325
See also: https://github.com/archlinuxcn/repo/issues/1351
Those files is created manually. Please check whether indicated maintainers in `lilac.yaml` are correct or not, thanks! @colinkeenan @felixonmars @heavysink @yuyichao
UPDATE 2019/11/15
d9f461855604c6821091e50a41388ab2dee1ae33 - I consider it a confirmation of llvm-julia maintenance.
344103f3f4253c7c7ed175c0ae7f8713596a7429 - confirmation of youtube-dl-git maintenance. See also https://github.com/archlinuxcn/repo/pull/1383.

Add lilac.yaml to remaining packages

---

archlinuxcn/litecli/lilac.py
archlinuxcn/litecli/lilac.yaml
archlinuxcn/mycli/lilac.py
archlinuxcn/mycli/lilac.yaml
archlinuxcn/python-sqlparse-cli_helpers/PKGBUILD
archlinuxcn/python-sqlparse-cli_helpers/lilac.yaml

#1378 #1398 
加了一个 python-sqlparse-cli_helpers 包到 repo 里，然后 mycli/litecli 的 python-sqlparse 依赖改成 python-sqlparse-cli_helpers 应该可以解决。
然后等 pypi 上游 setup.py 里的依赖能跟上 Arch 源里的版本再改回来就行了应该。

try to resolve mycli/litecli depends issue

---

archlinuxcn/hath/PKGBUILD

Bump the version of Hath from 1.4.2 to 1.6.0

Version bumping for hath.

---

archlinuxcn/qv2ray-dev-git/PKGBUILD

upstream changes:
- `qzxing` => `zxing-cpp` (use existing package in `extra` repo)
- deleted dependency of `qhttpserver`

qv2ray-dev-git: updating dependencies

---

archlinuxcn/qv2ray/PKGBUILD

Qv2ray v2.5.0 introduced plugin feature and removed its built-in PAC server.
The aforementioned dependency is no longer needed.

qv2ray: removing unused dependency

---

archlinuxcn/chromium-vaapi/lilac.yaml

Recent `re2` update (`1:20200401-1` -> `1:20200501-1`) breaks `chromium-vaapi`:
```
/usr/lib/chromium/chromium: error while loading shared libraries: libre2.so.6: cannot open shared object file: No such file or directory
```
I don't really know if it's how lilac works, but maybe we can rebuild `chromium-vaapi` on `re2` upgrades.

chromium-vaapi: Should rebuild on "re2" update

---

archlinuxcn/qv2ray/PKGBUILD
archlinuxcn/qv2ray/lilac.yaml

upstream `protobuf` bumped soversion recently.
a rebuilld is needed.

qv2ray: rebuild due to protobuf soversion bump

---

archlinuxcn/trojan-go-git/PKGBUILD

according to https://wiki.archlinux.org/index.php/Go_package_guidelines
```
❰ducksoft❙~❱✔≻ file /usr/lib/trojan-go/trojan-go
/usr/lib/trojan-go/trojan-go: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=a3beead5cfa934860e1acf128f29ba06003ca6a5, for GNU/Linux 3.2.0, stripped
```

trojan-go-git: enable PIE

---

.travis.yml
archlinuxcn/armadillo/lilac.yaml
archlinuxcn/fs-uae-arcade-devel/lilac.yaml
pre-commit

Marked as draft as this depends on https://github.com/archlinuxcn/lilac/pull/144. Will update after that pull request is merged or another approach is proposed.
See https://travis-ci.org/github/yan12125/repo/builds/673671061 for an example failing test.

Test for invalid repo_depends items (closes #1414)

---

pre-commit

When pre-commit is used as a git hook, iter_packages only goes through
changed packages, and dependent package may not be in `pkgs`.
Test:
1. Modify random stuffs in libqtxdg-git
2. Commit libqtxdg-git
Follow-up of #1574.

pre-commit: fix repo_depends check

---

archlinuxcn/dutree/PKGBUILD
archlinuxcn/mcfly/PKGBUILD
archlinuxcn/pijul/PKGBUILD

The extra `/` will cause 404 when trying to download crate.
This may help to fi.x #1718.
```bash
❯ curl -I https://crates.io//api/v1/crates/mcfly/0.4.0/download
HTTP/2 404
content-type: application/json; charset=utf-8
content-length: 35
server: nginx
date: Mon, 06 Jul 2020 04:49:53 GMT
strict-transport-security: max-age=31536000
via: 1.1 vegur, 1.1 73d3ff0182f526d6384b20c342c6483b.cloudfront.net (CloudFront)
x-cache: Error from cloudfront
x-amz-cf-pop: SFO20-C1
x-amz-cf-id: N7mxgowm2IGRSgqTHLO8DNxC3_2INLYfjAf0elzMh4mtQ1DcjXwrfg==
❯ curl -I https://crates.io/api/v1/crates/mcfly/0.4.0/download
HTTP/2 302
content-length: 0
location: https://static.crates.io/crates/mcfly/mcfly-0.4.0.crate
server: nginx
date: Mon, 06 Jul 2020 04:49:57 GMT
x-content-type-options: nosniff
x-frame-options: …
```

misc: fix crates.io url

---

archlinuxcn/emacs-native-comp-git/lilac.yaml

change the branch name from 'native-comp' to 'feature/native-comp'

emacs-native-comp-git: fix branch name in lilac.yaml

---

archlinuxcn/fcitx5-pinyin-moegirl/PKGBUILD
archlinuxcn/fcitx5-pinyin-moegirl/lilac.yaml

tl;dr, the repository path is changed to `outloudvi/mw2fcitx`. By the way:
`fcitx-pinyin-moegirl` has pivoted to a general-purposed MediaWiki-to-fcitx pip module called [`mw2fcitx`](https://pypi.org/project/mw2fcitx/). As a result:
1. The repository is renamed to `outloudvi/mw2fcitx`, which is what this PR is about.
2. The dictionary generating script is simplified to just one line of code: `mw2fcitx -c moegirl_dict.py` (the configuration file `moegirl_dict.py` is [here](https://github.com/outloudvi/mw2fcitx/blob/pkg-moegirl/utils/moegirl_dict.py))
Due to the eased process, maybe you want to generate the dictionary directly on the building machine. A normal generating process costs about over 90 minutes (considering moegirl.org.cn is in mainland China now) for a server outside mainland …

fcitx5-pinyin-moegirl: Change repo name

---

archlinuxcn/haskell-language-server-bin/lilac.yaml

Haskell language server was released 5 days ago with pre-built binaries. To Be Reviewed.

addpkg: haskell-language-server-bin

---

archlinuxcn/ghcide/lilac.yaml

Building under each ghc version takes a long time.

ghcide: loosen time restriction

---

archlinuxcn/adcli/PKGBUILD
archlinuxcn/adcli/lilac.yaml

[aur/adcli](https://aur.archlinux.org/packages/adcli/) is a simple and useful command line tool of interacting with Active Directory.

addpkg: adcli

---

archlinuxcn/ghcup-hs-bin/lilac.yaml

an alternative to bootstrap static ghc

addpkg: ghcup-hs-bin

---

archlinuxcn/cherrytree/PKGBUILD
archlinuxcn/cherrytree/lilac.yaml

CherryTree is an awesome app that enables users to take notes and manage them. It also supports rich formatting. This AUR package contains a complete build instructions for CherryTree, and I had successfully made it on my machine. It would be better for users to have a prebuilt package in the Archlinux CN repo.

addpkg: cherrytree

---

archlinuxcn/dhcptest-git/PKGBUILD
archlinuxcn/dhcptest-git/lilac.yaml

`dhcptest-git` is a useful tool of testing DHCP servers and viewing their responses.

addpkg: dhcptest-git

---

archlinuxcn/lilac-git/PKGBUILD
archlinuxcn/lilac-git/lilac.yaml

Depends on ongoing upstream PRs: https://github.com/archlinuxcn/lilac/pull/170, https://github.com/archlinuxcn/lilac/pull/171
@lilydjwg I bundled [build-cleaner](https://github.com/archlinuxcn/misc_scripts/blob/master/build-cleaner) in this package as it seems the simplest way. As you're the only contributor for that script, could you go ahead and declare a license for it?

addpkg: lilac-git

---

archlinuxcn/glmark2/PKGBUILD
archlinuxcn/glmark2/lilac.yaml

Seems that `glmark2` has a tagged release on GH at 2020.04 that has included the two patches.

Update glmark2 package and hook

---

archlinuxcn/python-pymupdf/PKGBUILD
archlinuxcn/python-pymupdf/lilac.yaml

related issue https://github.com/archlinuxcn/repo/issues/2001
lector-git could be trigger rebuilding after building python-pymupdf, and #2001 could be closed.

python-pymupdf: fix building with python 3.9 and code clean

---

archlinuxcn/sendanywhere/PKGBUILD

fix according to #2108 
> `vcs_update` expects them to be `SKIP`.

sendanywhere: skip validity check

---

archlinuxcn/buildkit/PKGBUILD
archlinuxcn/buildkit/lilac.py
archlinuxcn/buildkit/lilac.yaml
archlinuxcn/nerdctl/PKGBUILD
archlinuxcn/nerdctl/lilac.py
archlinuxcn/nerdctl/lilac.yaml
archlinuxcn/rootlesskit/PKGBUILD
archlinuxcn/rootlesskit/lilac.py
archlinuxcn/rootlesskit/lilac.yaml

`nerdctl` 是 `containerd` 的命令行终端，提供兼容`docker`的命令行参数。
这个PR主要是打包 [nerdctl](https://github.com/containerd/nerdctl) 以及它的依赖包
* [buildkit](https://github.com/moby/buildkit)  用于`nerdctl build`
* [rootlesskit](https://github.com/rootless-containers/rootlesskit) 用于在非root用户下使用`nerdctl`

addpkg: nerdctl

---

archlinuxcn/zsh-syntax-highlighting-git/PKGBUILD
archlinuxcn/zsh-syntax-highlighting-git/lilac.py
archlinuxcn/zsh-syntax-highlighting-git/lilac.yaml
archlinuxcn/zsh-syntax-highlighting-git/zsh-syntax-highlighting.install

The AUR package is unfortunatedly orphaned, so I adopted that package and I think it's a good idea to update it with lilac.

zsh-syntax-highlighting-git: update AUR package after build

---

archlinuxcn/shadowsocks-rust-opt-git/PKGBUILD
archlinuxcn/shadowsocks-rust-opt-git/lilac.py
archlinuxcn/shadowsocks-rust-opt-git/lilac.yaml
archlinuxcn/shadowsocks-rust-opt-git/shadowsocks-rust-server@.service
archlinuxcn/shadowsocks-rust-opt-git/shadowsocks-rust@.service

Same thing as `shadowsocks-rust-git`, but with modern instruction sets (like AVX2) enabled.
Huge performance and energy saving boost for most computers.
Drawbacks: Not for very old computers.

addpkg: shadowsocks-rust-opt-git

---

archlinuxcn/adguardhome/lilac.yaml
archlinuxcn/code-transparent/lilac.yaml
archlinuxcn/elvish/lilac.yaml
archlinuxcn/flacon/lilac.yaml
archlinuxcn/font-victor-mono/lilac.yaml
archlinuxcn/gitter/lilac.yaml
archlinuxcn/kreogist-mu/lilac.yaml
archlinuxcn/nvm/lilac.yaml
archlinuxcn/pencil/lilac.yaml
archlinuxcn/plex-hama-bundle-git/lilac.yaml
archlinuxcn/plex-media-server/lilac.yaml
archlinuxcn/scrcpy/lilac.yaml
archlinuxcn/ttf-merriweather-sans/lilac.yaml
archlinuxcn/ttf-merriweather/lilac.yaml
archlinuxcn/ttf-oswald/lilac.yaml
archlinuxcn/ttf-quintessential/lilac.yaml
archlinuxcn/ttf-signika/lilac.yaml

add explicit maintainers to aur_pre_build() calls.
affected packages:
- adguardhome
- code-transparent
- elvish
- flacon
- font-victor-mono
- gitter
- kreogist-mu
- nvm
- pencil
- plex-hama-bundle-git
- plex-media-server
- scrcpy
- ttf-merriweather-sans
- ttf-merriweather
- ttf-oswald
- ttf-quintessential
- ttf-signika
initiated by #2228

fix: harden aur_pre_build() of frantic1048's AUR packages

---

archlinuxcn/vim-youcompleteme-git/lilac.py

The upstream (AUR) recently added the `using system clang` option
https://aur.archlinux.org/cgit/aur.git/commit/?h=vim-youcompleteme-git&id=88d59671e2511f8bda3a5e812fd5009c5a95511c
And it used system clang in the past, and the packages in the repo are also configured to use system clang (https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/vim-youcompleteme-git/lilac.yaml#L14)
cc @dctxmei because it is maintained by he/she

feat(vim-youcompleteme-git): using system clang

---

archlinuxcn/nerdctl/PKGBUILD

修正 升级到 nerdctl 0.10 后，不能编译的问题。
https://github.com/containerd/nerdctl/releases/tag/v0.10.0
```
The Go package github.com/containerd/nerdctl was moved to github.com/containerd/nerdctl/cmd/nerdctl (#269)
Users using go install github.com/containerd/nerdctl will need to change their installation script to go install github.com/containerd/nerdctl/cmd/nerdctl
Users using make or the binary distribution are unaffected
```

fix: nerdctl 0.10.0 build command changed

---

archlinuxcn/telegram-desktop-git/PKGBUILD

After upgrade telegram-desktop-git, it crash after start.
```
$ telegram-desktop 
telegram-desktop: error while loading shared libraries: libjemalloc.so.2: cannot open shared object file: No such file or directory
```
It can working properly after install [extra/jemalloc](https://archlinux.org/packages/extra/x86_64/jemalloc/)

fix(telegram-desktop-git): Fix missing jemalloc runtime depends

---

archlinuxcn/grub-themes-git/PKGBUILD

虽然已经有了 <https://github.com/archlinuxcn/repo/pull/2479>，然而其提供的 PKGBUILD 并不能编译。
Fix #2482

grub-themes-git: fix info.png missing issue

---

archlinuxcn/bear/lilac.yaml

after grpc upgrade:
```
/usr/bin/intercept: error while loading shared libraries: libgrpc++.so.1.41: cannot open shared object file: No such file or directory
```
```
➜ ldd /usr/bin/intercept
linux-vdso.so.1 (0x00007ffeb459c000)
libprotobuf.so.28 => /usr/lib/libprotobuf.so.28 (0x00007f98248fb000)
libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f98248da000)
libgrpc++.so.1.41 => not found
libabsl_synchronization.so.2103.0.1 => not found
libspdlog.so.1 => /usr/lib/libspdlog.so.1 (0x00007f982485d000)
libfmt.so.8 => /usr/lib/libfmt.so.8 (0x00007f982483a000)
libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f9824831000)
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f982461b000)
libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f9824600000)
libc.so.6 => /usr/lib/libc.so.6 (0x00007f9824434000) …
```

bear: rebuild on grpc and protobuf

---

archlinuxcn/python-onnx/PKGBUILD

See: https://github.com/onnx/onnx/pull/3674
The partially-broken package was successfully built as tests are removed (108f7568f21c9c4d16cd3c16bc6059ae6957ae93).
Well, maybe I shouldn't tell people to remove tests (https://github.com/archlinuxcn/repo/issues/2564) instead of fixing them.

python-onnx: fix Python 3.10 compatibility

---

archlinuxcn/kdiskmark-git/PKGBUILD

```bash
❯ sudo pacman -Syu kdiskmark-git
:: Synchronizing package databases...
core is up to date
extra is up to date
community is up to date
multilib is up to date
archlinuxcn                                                  1942.4 KiB   719 KiB/s 00:03 [-----------------------------------------------------] 100%
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...
Package (1)                New Version          Net Change  Download Size
archlinuxcn/kdiskmark-git  2.3.0.r2.g9952d5f-1    0.39 MiB       0.14 MiB
Total Download Size:   0.14 MiB
Total Installed Size:  0.39 MiB
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
kdiskmark-git-2.3.0.r2.g9952d5f-1-x86_64                      138.3 KiB   207 KiB/s 00:01 …
```

kdiskmark-git: conflicts with kdiskmark

---

archlinuxcn/babel-eslint/PKGBUILD
archlinuxcn/joplin/PKGBUILD
archlinuxcn/pnpm/PKGBUILD

Since npm 7, the `--user` option is no longer available. `--user root` not only doesn't fix the permission problem, but also installs the package called "root", which conflicts with other packages that also have the `--user root` option.

fix: remove `npm --user root`

---

archlinuxcn/pcsx2-git/pcsx2.install

So it actually applies over the generated binary

Change target to lowercase

---

archlinuxcn/telegram-desktop-megumifox/0001-Use-QGuiApplication-font-instead-of-opensans.patch
archlinuxcn/telegram-desktop-megumifox/PKGBUILD
archlinuxcn/telegram-desktop-megumifox/lilac.yaml

allows the user to specify custom UI font family name by two environment variables:
TELEGRAM_DESKTOP_UI_FONT and TELEGRAM_DESKTOP_UI_FONT_MONO

telegram-desktop-megumifox: allow reading font family name from env

---

archlinuxcn/haruna/PKGBUILD

`haruna` requires `ffmpeg4.4`. Without it, an error about missing `libavutil.so` file will be thrown.

haruna: add missing depends

---

archlinuxcn/fish-git/PKGBUILD

source changed to git+https
caused by https://aur.archlinux.org/cgit/aur.git/commit/?h=fish-git&id=8a74fa0f47a7ae235e3ea7eed27c1efc40520d69
resolved #2747

fix fish-git

---

archlinuxcn/xrock-git/PKGBUILD
archlinuxcn/xrock-git/lilac.yaml

The low level tools for rockchip SOC with maskrom and loader mode support.
```bash
usage:
xrock maskrom <ddr> <usbplug> [--rc4-off] - Initial chip using ddr and usbplug in maskrom mode
xrock version                             - Show chip version
xrock capability                          - Show capability information
xrock reset [maskrom]                     - Reset chip to normal or maskrom mode
xrock hexdump <address> <length>          - Dumps memory region in hex
xrock dump <address> <length>             - Binary memory dump to stdout
xrock read <address> <length> <file>      - Read memory to file
xrock write <address> <file>              - Write file to memory
xrock exec <address>                      - Call function address
xrock flash                               - Detect flash and …
```

addpkg: xrock-git

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD
archlinuxcn/devtools-archlinuxcn/arch-nspawn-read-CacheDir-from-host.patch

To get rid of race conditions around the default pacman cache dir during
concurrent builds
This should fix the issue. I checked modified `pacman-*.conf` files but didn't actually test it.
```
$ tar -xOf devtools-archlinuxcn-20200407-2-any.pkg.tar.zst usr/share/devtools/pacman-extra.conf | grep CacheDir
#CacheDir    = /var/cache/pacman/pkg/
CacheDir=/data/archlinux/pool/packages/
CacheDir=/data/archlinux/pool/community/
CacheDir=/data/repo/x86_64/
```
As this package is marked with `managed: false`, it should be manually built and upload. I can do it if @farseerfc is OK with that.

devtools-archlinuxcn: arch-nspawn: read CacheDir option from host's conf

---

archlinuxcn/genie-systemd/PKGBUILD
archlinuxcn/genie-systemd/lilac.yaml

The PKGBUILD comes from upstream https://github.com/arkane-systems/genie/blob/master/PKGBUILD with a small change.
ca-certificates-vsign-universal-root is no longer needed.
Fix #2825

updpkg: genie-systemd

---

archlinuxcn/64gram-desktop/PKGBUILD
archlinuxcn/64gram-desktop/lilac.yaml

I found that 64gram-desktop commits so frequently, so I choose to use the release version.
fix https://github.com/archlinuxcn/repo/issues/2863
feel free to point out problems.

Add 64gram-desktop

---

archlinuxcn/motrix/PKGBUILD
archlinuxcn/motrix/lilac.yaml

When we use nodejs16 to build it, it won't pass.
So we add 2 patches to fix the probelm.
However, a new issue occured that when we open motrix for a long time,
a pop-up windows will say "cb is not a function."
This time, we use nodejs14 build motrix to avoid it.

motrix: use nvm to build

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

[archlinuxcn commits](https://github.com/archlinuxcn/devtools/compare/archlinux:devtools:master...master) are rebased without any conflict. Tested commits:
* [Revert "makechrootpkg: when installing with -I, ensure package is installed"](https://github.com/archlinux/devtools/commit/b10e507f78bacadc5a1dce434687c9335bf9999f)
* [Change default BUILDTOOL to devtools-archlinuxcn](https://github.com/archlinux/devtools/commit/5321b99e7a1a755675615b149cec7b1b6b9f07bf)
* [Silent while show errors for curl](https://github.com/archlinux/devtools/commit/9a369623002cd3ba9922e0123a294014a38466ff)
* [Use x86_64 mirrors for x86_64_v3](https://github.com/archlinux/devtools/commit/82f5c9bbc8ac055790345975131afa552527f323)
The other two commits are not tested.
Seems there are no breaking changes in [upstream …

devtools-archlinuxcn: update to 20221002

---

archlinuxcn/clash-meta/lilac.yaml
archlinuxcn/quickjs/lilac.yaml

fix `lilac.yaml` for `quickjs` and `clash-meta`
see the following logs for detail
- https://build.archlinuxcn.org/packages/#/clash-meta/logs/1664828294
- https://build.archlinuxcn.org/packages/#/clash-verge/logs/1664828294
- https://build.archlinuxcn.org/packages/#/quickjs/logs/1664828292

Fix: dependencies build failure for `clash-verge`

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

[archlinuxcn commits](https://github.com/archlinuxcn/devtools/compare/archlinux:devtools:master...master) are rebased without any conflict. Tested commits:
* [Revert "makechrootpkg: when installing with -I, ensure package is installed"](https://github.com/archlinuxcn/devtools/commit/b3465c467898b3e862dd207c8097d446460aeaf0)
* [Change default BUILDTOOL to devtools-archlinuxcn](https://github.com/archlinuxcn/devtools/commit/3e253e0e513b8fe470803888c28043c44fa669ba)
* [Silent while show errors for curl](https://github.com/archlinuxcn/devtools/commit/a502f6127cce505cad0ac7f3de90114a8087872d)
* [Use x86_64 mirrors for x86_64_v3](https://github.com/archlinuxcn/devtools/commit/a13784f1246c06f1db24487a306fd03b621dcb69)
The other two commits are not tested.
Also, seems there are no breaking …

devtools-archlinuxcn: update to 20221012

---

archlinuxcn/oh-my-posh/lilac.yaml

AUR上的更新和这里的自动更新基本上是重复的，当AUR更新后这里会对`pkgrel`进行更新生成一个与`x.x.x-1`一模一样的`x.x.x-2`，没有意义

oh-my-posh: 不随AUR更新

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

Also bumps $_upstream_pkgrel following
https://github.com/archlinux/svntogit-packages/commit/558e0aad0c4a123ad8602f4cc5af7a149785c1d6
Closes https://github.com/archlinuxcn/repo/issues/3060

devtools-archlinuxcn: fix pacstrap incompatibility

---

archlinuxcn/clash-meta/PKGBUILD

编译时包含 tun 模式必要的 gvisor 
https://github.com/MetaCubeX/Clash.Meta/blob/667f42dcdcaacfef0c6cd84d38267d5971315f0d/Makefile#L15
添加使用 tun 模式时必要的 capabilities
https://github.com/zzzgydi/clash-verge/issues/182

修复 clash-meta 使用 tun 模式时的打包错误

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

[archlinuxcn commits](https://github.com/archlinuxcn/devtools/compare/archlinux:devtools:master...master) are rebased without any conflict. This time I test only the new archlinuxcn-specific patch (https://github.com/archlinuxcn/devtools/pull/1) and skip existing ones.
There is one noticeable change in [upstream commits](https://github.com/archlinux/devtools/compare/20221012...20230105): debug packages are enabled by default. There are already several debug packages in [archlinuxcn], so it should work in general. Possible issues may include broken builds with debug flags or disk usage for mirrors.

devtools-archlinuxcn: update to 20230105

---

archlinuxcn/clash-verge/PKGBUILD

add `libappindicator-gtk3` `libayatana-appindicator` to `depends`,  remove version constraint of `clash-premium-bin` in `makedepends`.
This should fix #3107

clash-verge: update depends

---

archlinuxcn/librime-sbxlm-git/0001-fix-build.patch

gtest 1.13 不再支持 c++ 11 了，需要将 c++ standard 设置为 c++14 ，经过测试后能够使用，这段文字就是用这个 patch 后的版本输入的

librime-sbxlm: fix build error with gtest-1.13

---

archlinuxcn/notepad---git/PKGBUILD
archlinuxcn/notepad---git/lilac.yaml

notepad--是一个国产跨平台、简单的文本编辑器，是替换notepad++的一种选择。其内置强大的代码对比功能，让你丢掉付费的beyond compare。

Add notepad---git

---

archlinuxcn/clash-verge/PKGBUILD

According  to [tauri doc](https://tauri.app/v1/guides/features/system-tray/#linux-setup), only one of  `'libappindicator-gtk3'` `'libayatana-appindicator'` is needed, but  ` libappindicator-gtk3` breaks left-mouse actions for most applications Edit, see https://bugs.launchpad.net/ubuntu/+source/libappindicator/+bug/1910521
we decide to remove it from `depends` list.
Thank [stonemoe](https://aur.archlinux.org/account/stonemoe) from AUR for informing me of this.

clash-verge: rm libappindicator-gtk3 from depends

---

archlinuxcn/clash-meta/clash-meta@.service

clash-meta@sevice服务的CapabilityBoundingSet和AmbientCapabilities有问题，导致无法systemctl无法使用非root用户成功启动服务，这应修改为与Clash.Meta文档一样 https://github.com/MetaCubeX/Clash.Meta#general-installation-guide-for-linux
CapabilityBoundingSet=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_ADMIN CAP_NET_RAW CAP_NET_BIND_SERVICE

修复 clash-meta 的 clash-meta@.service 文件错误

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD
archlinuxcn/devtools-archlinuxcn/lilac.yaml

Also adds myself to maintainers, so that I can receive package notifications
---
I will still use pull requests to update this package in the future, so that people can have a look before new devtools enter [archlinuxcn].
There is one conflict: the patch from https://github.com/archlinuxcn/devtools/pull/1 conflicts with another one from https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/122. With a quick test, the option `-t` seems still working. I didn't test other archlinuxcn-specific patches.
Also, seems there are no breaking changes in [upstream commits](https://github.com/archlinux/devtools/compare/20230105...20230307).

devtools-archlinuxcn: update to 20230307

---

archlinuxcn/librime-sbxlm-git/0001-fix-build.patch
archlinuxcn/librime-sbxlm-git/PKGBUILD

上游已经更新到 c++14 了，移除设置 c++14 的 patch，修复打包失败的问题

fix(librime-sbxlm-git): remove c++14 flag patch

---

archlinuxcn/clash-verge/PKGBUILD

Hello, I'm the maintainer of this pkg (check on [aur](https://aur.archlinux.org/packages/clash-verge) and its [yaml](https://github.com/archlinuxcn/repo/blob/master/archlinuxcn/clash-verge/lilac.yaml) )
this pr fixes crash on launch, and support granting permission on linux,  see https://github.com/zzzgydi/clash-verge/commit/2b6acedae1fa29646e10cee4483105fa3479a2d6 and https://github.com/zzzgydi/clash-verge/commit/52658886e75cd2f06fb125fcb74da5a3452275e5

clash-verge: bump version to 1.3.0 and fix crash

---

alarmcn/elan-lean/PKGBUILD
alarmcn/elan-lean/lilac.yaml
alarmcn/elan-lean/post.install
archlinuxcn/elan-lean/PKGBUILD

This PR add support for aarch64 for package elan-lean.
[lean4-nightly](https://github.com/leanprover/lean4-nightly/releases) 提供了 lean4 的对应架构的二进制版本，asahi 用户也可以使用。

elan-lean: add aarch64 support

---

archlinuxcn/clash-verge/PKGBUILD

Hello, I'm the maintainer of clash-verge.  clash-verge-1.3.1 failed to be built(see https://build.archlinuxcn.org/packages/#/clash-verge/logs/1681255472)  as the patches are no longer needed. 
They  are already included in newer version of clash-verge.
This pr removes these patches and makes it to compile.

clash-verge: fix building failure

---

archlinuxcn/clash-meta/PKGBUILD

Hello, I'm the maintainer of this package in [AUR](https://aur.archlinux.org/packages/clash-meta). 
I don't know why its shasum should be wrong but when I run `updpkgsums` it changes indeed. 
This pr corrects its shasum.

clash-meta: updpkgsums

---

archlinuxcn/xone-dkms-git/PKGBUILD

Arch kernel 6.3.1 is live, but xone upstream hasn't merge the fix, so fix it here to avoid breakage.

xone-dkms-git: Fix build on 6.3

---

archlinuxcn/gdb-multiarch/PKGBUILD
archlinuxcn/gdb-multiarch/lilac.yaml

Currently the gdb's sim folder contains problematic code that cannot be compiled and linked without any error if LTO option is on. However the simulator executables are not added into the output package and have been probably obsoleted in many Linux distributions, like [Debian](https://salsa.debian.org/gdb-team/gdb/-/blob/debian/13.1-2/debian/rules?ref_type=tags#L204). To avoid failures when building the package with Archlinux's devtools, the '--disable-sim' option is added to the configuration command-line to disable these files. In addition, syncing with upstream AUR repository is temporarily disabled until the upstream no longer has this problem, but I'm not sure whether it's necessary to and how to add another sources, like the official release, to keep the package always up-to-date.

gdb-multiarch: disable build for simulators

---

archlinuxcn/wine-for-wechat/wine-wechat.patch

修复微信聊天信息无法打开的问题
点击聊天界面的三个点按钮或者点击顶部title无法打开聊天详情

fix: 修复微信聊天信息窗口无法打开的问题

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

PKGBUILD is synced again from
https://gitlab.archlinux.org/archlinux/packaging/packages/devtools/
Rebase conflicts:
* Change default BUILDTOOL to devtools-archlinuxcn
* Use x86_64 mirrors for x86_64_v3
Those two commits are tested.
---
There are many [upstream commits](https://github.com/archlinux/devtools/compare/20230307...1.0.0). Most of them are related to git migration. There is one known issue: `offload-build` may fail if the server and the client has different devtools versions [1]
[1] https://gitlab.archlinux.org/archlinux/devtools/-/issues/108

devtools-archlinuxcn: update to 1.0.0

---

archlinuxcn/clash-verge/PKGBUILD

Hello, I'm the maintainer of this package.  This pr fixes the build failure in 1.3.2 (perhaps only on archlinux)
Though I don't know the reason, it just works. (Tested locally with `archlinuxcn-x86_64-build`)
Similar issues are https://github.com/briansmith/ring/issues/1444

[clash-verge]: fix build failure in 1.3.2

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

I only do basic smoke testing by building devtools-archlinuxcn itself.
There are no rebase conflicts, and [upstream commits](https://github.com/archlinux/devtools/compare/v1.0.1...v1.0.2) look trivial.

devtools-archlinuxcn: update to 1.0.2

---

archlinuxcn/retext-git/PKGBUILD

Should upgrade to qt6 to fix the long-standing error. PKGBUILD copied from https://gitlab.archlinux.org/archlinux/packaging/packages/retext/-/blob/main/PKGBUILD

retext-git: follow upstream, upgrading to qt6

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

I only do basic smoke testing by building a random AUR package.
There are no rebase conflicts, and [upstream commits](https://github.com/archlinux/devtools/compare/v1.0.2...v1.0.3) look trivial.

devtools-archlinuxcn: update to 1.0.3

---

archlinuxcn/balena-etcher/lilac.yaml
archlinuxcn/electron19-bin/PKGBUILD
archlinuxcn/electron19-bin/lilac.yaml

Electron19 is not in official now, archlinuxcn need to provide electron19-bin for balena-etcher

fix balena-etcher build

---

archlinuxcn/amd-vulkan-prefixes/PKGBUILD
archlinuxcn/amd-vulkan-prefixes/lilac.yaml

as the amdgpu users, we can use the scripts in this package
to chose the specify vulkan driver for application that use graphics gpu
the wiki page [Vulkan#Selecting_via_AMD_Vulkan_Prefixes](https://wiki.archlinux.org/title/Vulkan#Selecting_via_AMD_Vulkan_Prefixes) and cnwiki [Vulkan#通过_AMD_Vulkan_Prefixes_选择](https://wiki.archlinuxcn.org/wiki/Vulkan#%E9%80%9A%E8%BF%87_AMD_Vulkan_Prefixes_%E9%80%89%E6%8B%A9) also references the package exactly

add amd-vulkan-prefixes

---

archlinuxcn/wiliwili/PKGBUILD
archlinuxcn/wiliwili/lilac.yaml

[wiliwili](https://github.com/xfangfang/wiliwili), 专为手柄控制设计的第三方跨平台B站客户端（当然，也肯定也是可以在 Archlinux 上正常工作的）

Add wiliwili

---

archlinuxcn/xorg-xwayland-lily/hidpi.patch
archlinuxcn/xorg-xwayland-lily/lilac.py
archlinuxcn/xorg-xwayland-lily/lilac.yaml

While `xwl_screen_validate_property_access` is in the code, it isn't registered as a callback so using `xprop` at runtime still works.

xorg-xwayland-lily: refresh patch

---

archlinuxcn/python-cambd/PKGBUILD
archlinuxcn/python-cambd/lilac.yaml

[`python-cambd`](https://github.com/rocktimsaikia/cambd/) is a simple Cambridge Dictionary cli app, written in Python, published under MIT license.

Add python-cambd

---

archlinuxcn/telegram-desktop-megumifox/lilac.yaml

Now that glibmm-2.68 2.78.0-1 has landed in arch, we can follow upstream versions again.

telegram-desktop-megumifox: bring back auto updates

---

archlinuxcn/mesa-git/lilac.yaml

it wasn't building before, and some good changes from other software

fix(mesa-git): fixing lilac.yaml to make mesa-git build

---

archlinuxcn/revda-git/PKGBUILD
archlinuxcn/revda-git/lilac.yaml

This makes it so that this package no longer owns /usr/local and /usr/local/bin
Builds fine for me in a clean chroot, also the resulting package works for me.

revda-git: use cmake instead of directly invoking ninja

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

Also replaces bzr by breezy
See: https://gitlab.archlinux.org/archlinux/packaging/packages/devtools/-/commit/50f0b46b1c31f4e478e597688ce825ad68942340
See: https://archlinux.org/todo/change-dependency-from-bzr-to-breezy/
---
I only do basic smoke testing by building devtools-archlinuxcn itself.
There are no rebase conflicts, and [upstream commits](https://github.com/archlinux/devtools/compare/v1.0.3...v1.0.4) look trivial.

devtools-archlinuxcn: update to 1.0.4

---

archlinuxcn/telegram-desktop-megumifox/PKGBUILD

The .BUILDINFO of telegram-desktop 4.10.3-2 in the official repos package seems to have 
```
installed = qt6-base-6.6.0-1-x86_64
installed = qt6-declarative-6.6.0-1-x86_64
installed = qt6-imageformats-6.5.3-1-x86_64
installed = qt6-svg-6.6.0-1-x86_64
installed = qt6-translations-6.5.3-1-any
installed = qt6-wayland-6.5.3-1-x86_64
```
While qt6-wayland 6.6.0-1 [removed](https://gitlab.archlinux.org/archlinux/packaging/packages/qt6-wayland/-/commit/67c9415ad8ce4372b9699a14114f4729470a581e) its libxcomposite dependency which was only pulled in as a transitive dep through this qt6-wayland.
I guess that's why the official repo package builds while our builds failed...

telegram-desktop-megumifox: depend on libxcomposite

---

archlinuxcn/screengrab-git/PKGBUILD
archlinuxcn/screengrab-git/lilac.yaml

I maintain https://aur.archlinux.org/packages/screengrab-git but not this package, so syncing PKGBUILD is not trivial. This time, I update both manually.

screengrab-git: Rename kf5 packages

---

archlinuxcn/latte-dock-git/PKGBUILD

The upstream changes the name of the plasma-framework and knewstuff:
https://archlinux.org/packages/extra/x86_64/plasma-framework5/
https://archlinux.org/packages/extra/x86_64/knewstuff5/

Updated depenedncy name of latte-dock

---

archlinuxcn/hysteria/PKGBUILD

Diff: https://github.com/apernet/hysteria/compare/app/v2.1.0...app/v2.1.1
Changelog: https://github.com/apernet/hysteria/releases/tag/app%2Fv2.1.1
Fix #3513
```
$ namcap PKGBUILD
$ namcap hysteria-2.1.1-1-x86_64.pkg.tar.zst 
hysteria W: Directory (etc/hysteria) is empty
hysteria W: Dependency included, but may not be needed ('acl')
hysteria W: Dependency included, but may not be needed ('shadow')
```

hysteria: 2.1.0 -> 2.1.1

---

archlinuxcn/nali-go/PKGBUILD

使用从 archlinuxcn 安装的 nali-go 时，发现执行 `nali --version` 后，输出为 `nali version unknown version`。
查看代码后，认为原因是：nali-go 依赖编译时的 `-ldflags -X` 参数注入版本信息，上游代码中 Version 变量的导入路径发生过变化，导致 archlinuxcn 仓库中 PKGBUILD 产出的二进制没有正确的版本信息。
```diff
- github.com/zu1k/nali/constant.Version
+ github.com/zu1k/nali/internal/constant.Version
```
另外对比 AUR 中 nali-go 的 PKGBUILD，同步了一些变更到 archlinuxcn repo 中。
不是很熟悉 PKGBUILD，希望不要引入更多预期外问题，设置了 `Allow edits by maintainers`，有什么想法也可以直接修改这个 PR 的内容。
PS:
+ 我参考的 PKGBUILD: <https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=nali-go&id=c142319c85e4a0fab5cc0e85de9fd064750fc2e2>

nali-go: fix unknown version error

---

archlinuxcn/nheko-git/PKGBUILD

Upstream [removed](https://github.com/Nheko-Reborn/nheko/commit/87c063b112b8c7dc1a858af8406008da48b5260b) this option as Qt6 does AOT for qml by default.

nheko-git: Remove COMPILE_QML from cmake options

---

archlinuxcn/nheko-git/PKGBUILD
archlinuxcn/nheko-git/lilac.yaml

Newer versions of namcap seem to have started to output errors for the legacy license notation.
Also building this takes only ~2mins on the build machine, I don't think such a long throttle is needed...

nheko-git: Use SPDX license identifier and remove lilac throttle

---

archlinuxcn/feeluown-git/PKGBUILD

Ref #3587 
authy: Will drop package because we have no permission to redistribute, and license is unset.
crow-translate: AUR updated
feeluown-git: AUR and repo update
netease-cloud-music-gtk4: AUR maintainer notified
php-swoole: AUR maintainer notified
protontricks: AUR maintainer notified

Follow Arch Linux RFC16 (Bruceutut packages)

---

archlinuxcn/xone-dkms-git/PKGBUILD

Upstream introduced a new directory (`auth/`) that are left out by our package(). Let's fix just that.

xone-dkms-git: fix missing source files

---

archlinuxcn/telegram-desktop-lily/lilac.yaml
archlinuxcn/telegram-desktop-megumifox/lilac.yaml

`readelf -d /usr/bin/telegram-desktop` contains libvpx.so.8 so it's a direct dependency.
The PKGBUILD should also probably be modified to include libvpx as a dependecy...

telegram-desktop-{lily,megumifox}: Rebuild on libvpx soname bump

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

PKGBUILD is synced again from
https://gitlab.archlinux.org/archlinux/packaging/packages/devtools/
Rebase conflicts:
* makechrootpkg: support bind mount tmpfs besides existing directories
---
No testing is carried out
There are many [upstream commits](https://github.com/archlinux/devtools/compare/v1.0.4...v1.1.0). Most of them are related to the `pkgctl` command and probably unrelated to archlinuxcn.
In [1.1.0-archlinuxcn1](https://github.com/archlinuxcn/devtools/tree/1.1.0-archlinuxcn1), I cherry-picked two upstream commits, which are already backported via upstream [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/devtools/-/blob/main/PKGBUILD)

devtools-archlinuxcn: update to 1.1.1

---

archlinuxcn/video-trimmer/lilac.yaml

Sorry for having made a mistake of release/tag
URL: YaLTeR/video-trimmer/-/releases/v0.8.2
the "v0.8.2" is tag

video-trimmer: fix lilac.yaml

---

archlinuxcn/wiliwili/PKGBUILD
archlinuxcn/wiliwili/lilac.yaml

Also dynamically linked to [tinyxml2](https://archlinux.org/packages/extra/x86_64/tinyxml2/)

wiliwili: fix build error caused by missing `libxinerama` at makedepends

---

archlinuxcn/paru-git/lilac.yaml
archlinuxcn/paru/lilac.yaml

Paru 2.0.3 already builds w/ pacman 6.1, so just trigger a rebuild.

paru{,-git}: rebuild on libalpm.so

---

archlinuxcn/yay-git/lilac.yaml

Same as #3697, but for yay-git.
The yay package has update_on aur, and the maintainer of the corresponding aur package seems to bump the pkgrel on pacman updates, so we can maybe get away with not adding this there.

yay-git: rebuild on libalpm.so

---

archlinuxcn/clash-verge/PKGBUILD

fix [issue#3688](https://github.com/archlinuxcn/repo/issues/3688)

clash-verge: use logo.bak.svg be icon

---

archlinuxcn/64gram-desktop/lilac.yaml

```64gram-desktop: error while loading shared libraries: libabsl_strings.so.2308.0.0: cannot open shared object file: No such file or directory```

fix 64gram

---

archlinuxcn/amberol/PKGBUILD
archlinuxcn/amberol/lilac.yaml

PKGBUILD: tested by archlinuxcn-x86_64-build
```
cat amberol-0.10.3-1-x86_64.pkg.tar.zst-namcap.log:
amberol W: ELF file ('usr/bin/amberol') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
amberol W: Unused shared library '/usr/lib/libgstvideo-1.0.so.0' by file ('usr/bin/amberol')
amberol W: Unused shared library '/usr/lib/libpango-1.0.so.0' by file ('usr/bin/amberol')
amberol W: Unused shared library '/usr/lib/libcairo.so.2' by file ('usr/bin/amberol')
```
lilac.yaml: tested locally successfully, got the right pkgverl:
```
[D 03-24 23:39:27.053 worker:214] got input: {'depend_packages': [], 'update_info': [[None, '0.10.3']],
```

amberol: Add package

---

archlinuxcn/sing-geoip/lilac.yaml
archlinuxcn/sing-geosite/lilac.yaml

我是 AUR [`sing-geoip`](https://aur.archlinux.org/pkgbase/sing-geoip) 和 [`sing-geosite`](https://aur.archlinux.org/pkgbase/sing-geosite) 的维护者，现在是想能让 CN 的这两个包和 AUR 中的同步更新

feat: update AUR repo when `sing-geoip` and `sing-geosite` are updated

---

archlinuxcn/clash-meta/PKGBUILD

现在沿用上游的设置`CGO_ENABLED=0`会构建出错, 调整为 `CGO_ENABLED=1` 可以构建成功。构建命令： `archlinuxcn-x86_64-build`
```
==> Starting build()...
go: downloading go.uber.org/automaxprocs v1.5.3
...
...
go: downloading github.com/pierrec/lz4/v4 v4.1.14
-linkmode requires external (cgo) linking, but cgo is not enabled
==> ERROR: A failure occurred in build().
```

clash-meta: set `CGO_ENABLED=1` to avoid build failure

---

archlinuxcn/telegram-desktop-megumifox/PKGBUILD

Same as #3745, but for telegram-desktop-megumifox.
Fixes #3744

telegram-desktop-megumifox: fix build

---

archlinuxcn/telegram-desktop-lily/PKGBUILD

https://gitlab.archlinux.org/archlinux/packaging/packages/glib2/-/commit/faec2cd2cd553d1fda9446aaeade85fc0f3722ec Degraded python-packaging to an optdep of glib2.

telegram-desktop-lily: fix build

---

archlinuxcn/telegram-desktop-lily/PKGBUILD

telegram-desktop-lily: add missing libxdamage dependency

---

archlinuxcn/telegram-desktop-megumifox/PKGBUILD

Arch did the same in https://gitlab.archlinux.org/archlinux/packaging/packages/telegram-desktop/-/commit/ce14d32d889285a4194fc9ec29c6308e08331c9c, not sure why did it build before...

telegram-desktop-megumifox: add missing libxdamage dependency

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

PKGBUILD is synced with extra/devtools again
Rebase conflicts:
* `makechrootpkg: support bind mount tmpfs besides existing directories` conflicts with [1]
* `Handle ArchLinuxARM server URL in arch-nspawn" conflicts with` conflicts with [2]
* `Revert "makechrootpkg: when installing with -I, ensure package is installed"` not needed after [1]
[1] https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/245
[2] https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/244
---
Some other notes:
* I only test building this package. More testing is necessary.
* sudoers may need to allow a new environment variable `LOGDEST`. I got the following error with `offload-build --server build.archlinuxcn.org`:
```
sudo: sorry, you are not allowed to set the following environment variables: …
```

devtools-archlinuxcn: update to 1.2.0

---

archlinuxcn/llvm-git/PKGBUILD
archlinuxcn/llvm-git/lilac.yaml

because of rational decision that i've seen, it wants the git version of spirv-tools-git

fix(llvm-git): adding spirv-tools-git

---

archlinuxcn/lib32-spirv-tools-git/PKGBUILD
archlinuxcn/lib32-spirv-tools-git/lilac.yaml

in my local copy lib32-llvm-git has multiple changes which enable lib32 llvm translator

feat(lib32-spirv-tools-git): adding lib32-spirv-tools-git

---

archlinuxcn/lib32-llvm-git/lilac.yaml

adding the dependant packages of the split package so things build

fix(lib32-llvm-git): fixing lilac.yaml

---

archlinuxcn/lib32-llvm-git/lilac.yaml

necessary repo_makedepends according to the logs of lilac

fix(lib32-llvm-git): adding spirv-tools-git

---

archlinuxcn/clash-verge/PKGBUILD

Upstream has removed `logo.bak.svg`. There is no need for an explicit install now

clash-verge: fix icon file

---

archlinuxcn/clash-verge/PKGBUILD

Removed makedepends `cargo-tauri`. Build the app with `cargo` now, with `tauri-app` at branch `1.x`.

clash-verge: fix 1.6.5 build issue

---

archlinuxcn/clash-verge/PKGBUILD

The new version of clash-verge call verge-mihomo which is just clash-meta. And the process-name need to be verge-mihomo also, so here use a hard link

clash-verge: fix mihomo name

---

archlinuxcn/clash-verge/PKGBUILD

Sorry for the mistake, the hard link will point to the compile machine's clash-meta.
And the soft link also can create a new progress name which is verge-mihomo.
So here should be soft link

clash-verge: soft link clash-meta to verge-mihomo

---

archlinuxcn/electron25-bin/PKGBUILD
archlinuxcn/electron25-bin/lilac.yaml

tested in extra-x86-64_build, namcap shown:
```
PKGBUILD (electron25-bin) W: Reference to x86_64 should be changed to $CARCH
PKGBUILD (electron25-bin) W: Reference to x86_64 should be changed to $CARCH
electron25-bin W: ELF file ('usr/lib/electron25/chrome-sandbox') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/chrome_crashpad_handler') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/chromedriver') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/electron') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/libEGL.so') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
electron25-bin W: ELF file ('usr/lib/electron25/libGLESv2.so') lacks …
```

electron25-bin: Add package

---

archlinuxcn/butterfly/PKGBUILD
archlinuxcn/butterfly/butterfly.sh
archlinuxcn/butterfly/lilac.yaml

test in extra-x86_64-build with dependence "fvm"(in #3727). namcap:
```
butterfly E: ELF file ('usr/share/butterfly/butterfly') outside of a valid path.
butterfly W: ELF file ('usr/lib/butterfly/libapp.so') lacks FULL RELRO, check LDFLAGS.
butterfly W: ELF file ('usr/lib/butterfly/libapp.so') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
butterfly W: ELF file ('usr/lib/butterfly/libflutter_linux_gtk.so') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
butterfly W: ELF file ('usr/lib/butterfly/libpdfium.so') lacks GNU_PROPERTY_X86_FEATURE_1_SHSTK.
butterfly W: Referenced library 'libdynamic_color_plugin.so' is an uninstalled dependency (needed in files ['usr/share/butterfly/butterfly'])
butterfly W: Referenced library 'liburl_launcher_linux_plugin.so' is an uninstalled dependency (needed in files …
```

butterfly: Add package

---

archlinuxcn/v2raya-core/PKGBUILD
archlinuxcn/v2raya-core/lilac.yaml
archlinuxcn/v2raya/PKGBUILD
archlinuxcn/v2raya/lilac.yaml

xray provides `v2raya-core` since https://github.com/archlinuxcn/repo/commit/a45645ba7ea57e2d3b0753b5b41667f2e97df87b

v2raya: depends on v2raya-core

---

README.md

archlinuxcn-keyring is now packaged by Felix Yan.
This reverts commit b084f50e1e76da77db11bf673af3df9d467e5f7d.

Revert "update README about farseerfc key"

---

archlinuxcn/serenity/PKGBUILD
archlinuxcn/serenity/lilac.yaml

[serenity](https://github.com/SagerNet/serenity): The configuration generator for sing-box
https://aur.archlinux.org/packages/serenity
- [PKGBUILD-namcap.log](https://github.com/user-attachments/files/16216186/PKGBUILD-namcap.log)
- [serenity-1.0.0_beta.13-2-x86_64.pkg.tar.zst-namcap.log](https://github.com/user-attachments/files/16216187/serenity-1.0.0_beta.13-2-x86_64.pkg.tar.zst-namcap.log)
- [serenity-1.0.0_beta.13-2-x86_64-build.log](https://github.com/user-attachments/files/16216188/serenity-1.0.0_beta.13-2-x86_64-build.log)
- [serenity-1.0.0_beta.13-2-x86_64-check.log](https://github.com/user-attachments/files/16216189/serenity-1.0.0_beta.13-2-x86_64-check.log)
- [serenity-1.0.0_beta.13-2-x86_64-package.log](https://github.com/user-attachments/files/16216190/serenity-1.0.0_beta.13-2 …

addpkg: serenity

---

archlinuxcn/waypipe/lilac.yaml

waypipe: error while loading shared libraries: libavcodec.so.60: cannot open shared object file: No such file or directory

waypipe: update_on ffmpeg

---

archlinuxcn/ocaml-menhir/lilac.yaml

The update from ocaml 5.1.0 to 5.1.1 causes the build of herdtools7-git to fail with error:
Error: Files /usr/lib/ocaml/menhirLib/menhirLib.cmxa
and /usr/lib/ocaml/stdlib.cmxa
make inconsistent assumptions over implementation Stdlib__Sys
AFAICT, this is caused by changes/recompilation of the standard library and is fixed by recompiling menhir.
It seems that just triggering rebuild on minor version update is not enough. I don't know if triggering on pkgrel update is necessary but it's included here just to be safe.
This may need to be applied to other ocaml packages.

[ocaml-menhir] More aggressive autobuild trigger when ocaml is updated

---

archlinuxcn/yuzu-early-access/0001-fix-fmt11.patch
archlinuxcn/yuzu-early-access/0002-fix-mem.patch
archlinuxcn/yuzu-early-access/PKGBUILD

This pr fixes build failure with `fmt-11.0.2-1`. ref:https://build.archlinuxcn.org/imlonghao-api/pkg/yuzu-early-access/log/1726177678
Also, some parts of PKGBUILD have been rewritten.
tested locally with `archlinuxcn-x86_64-build`.

yuzu-early-access: fix build for `fmt-11.0.2`

---

archlinuxcn/lceda-pro/PKGBUILD

upgpkg: lceda-pro 2.2.32.3-1

---

archlinuxcn/gtk3-lily/0001-inhibit-hex-check.patch
archlinuxcn/gtk3-lily/PKGBUILD

The patch can be found at https://github.com/XeCycle/gtk/tree/drop-unicode-input.

gtk3-lily: add patch to inhibit Ctrl-Shift-U unicode input

---

archlinuxcn/devtools-archlinuxcn/PKGBUILD

* Update dependencies following https://gitlab.archlinux.org/archlinux/packaging/packages/devtools/-/commit/a58ac354b286129fac1fa01f82ce135dce422829
---
* One conflict between https://github.com/archlinuxcn/devtools/commit/1ddd4c93c471d9adeb892d03f3591299dd1568f1 and https://gitlab.archlinux.org/archlinux/devtools/-/merge_requests/287. I didn't test it as I'm not sure what's the rationale behind the new local commit.
* I only test building this package. More testing is necessary.
* [Upstream commits](https://github.com/archlinux/devtools/compare/v1.2.1...v1.3.0) include some non-trivial changes and may need more checking.

devtools-archlinuxcn: update to 1.3.0

---

archlinuxcn/clash-meta/PKGBUILD

删除 clash-meta 的 conflicts 字段以避免如下情况。 （由  archlinuxcn tg群组用户 @IdeaPocket 报告。）
> 我自己整了个空包provide那些我觉得用不上的被依赖的包,之前我没用源里的clash-meta但是verge依赖Meta,就把meta加进去了,然后触发了冲突
> 这回想用回源里的meta后发生了冲突,不然要自己改PKGBUILD重新安装那个空包
ps: 直接改 AUR包不行，lilac会检测到有更新，然后用仓库的覆盖AUR的。

clash-meta: remove `conflicts`

---

archlinuxcn/linux-clear/lilac.yaml
archlinuxcn/linux-clear/package.list

The linux-clear-x64-v3 built in 2024 is still retained in the repository.

linux-clear: replace linux-clear-x64-v3 with linux-clear in package.list

---

archlinuxcn/tela-icon-theme-git/PKGBUILD

Debug symbols are unnecessary for this package.

tela-icon-theme-git: disable debug in options

---

archlinuxcn/dufs/dufs.service
archlinuxcn/dufs/dufs@.service
archlinuxcn/dufs/lilac.yaml

https://github.com/sigoden/dufs/issues/506
在服务启动后修正 socket 的权限。
```txt
puqns67@elaina ~> sudo systemctl restart dufs.service
puqns67@elaina ~> la /run/dufs
srwxr-xr-x - dufs dufs 2025/04/20 21:51:14 storage.socket
puqns67@elaina ~> paru -U dufs-0.43.0-3-x86_64.pkg.tar.zst
...
puqns67@elaina ~> sudo systemctl restart dufs.service
puqns67@elaina ~> la /run/dufs
srw-rw---- - dufs dufs 2025/04/20 21:51:46 storage.socket
```

dufs: fix permissions of UNIX sockets

---

archlinuxcn/fotema/PKGBUILD
archlinuxcn/fotema/lilac.yaml

otherwise would crash with could not load the library at `libonnxruntime.so`: DlOpen { desc: "libmpi.so.40: cannot open shared object file: No such file or directory" } when face detection is enabled

fotema: add missing dependency openmpi

---

archlinuxcn/rustdesk-server/PKGBUILD
archlinuxcn/rustdesk-server/lilac.yaml
archlinuxcn/rustdesk-server/rustdesk-server-hbbr.default
archlinuxcn/rustdesk-server/rustdesk-server-hbbr.service
archlinuxcn/rustdesk-server/rustdesk-server-hbbs.default
archlinuxcn/rustdesk-server/rustdesk-server-hbbs.service
archlinuxcn/rustdesk-server/rustdesk-server-sysusers.conf
archlinuxcn/rustdesk-server/rustdesk-server-tmpfiles.conf

打包 [Rustdesk](https://github.com/rustdesk/rustdesk) 的[服务端](https://github.com/rustdesk/rustdesk-server)，作为仓库中已有的 Rustdesk 的补充。

rustdesk-server: new package

---

archlinuxcn/portable/PKGBUILD

mimeapps.list does not exist anymore

Fix: portable

---

archlinuxcn/zen-browser/lilac.yaml

由于此包已由 @heavysink 维护，但 AUR 中的包还在我的名下，之前有问过 @heavysink 是否可以一起维护 AUR 中的包，没有得到回应，现打算弃置掉 AUR 中的包，故移除自动更新 AUR 的操作。我将在合并后从共同维护者中清除 lilac，并弃置此包。

zen-browser: remove update_aur_repo

---

alarmcn/ceccomp/PKGBUILD
archlinuxcn/ceccomp/PKGBUILD

最新的版本中更新了`configure`，可以把丑陋的workaround去掉了

ceccomp: apply new configure features

---

archlinuxcn/c001apk-flutter-git/lilac.yaml
archlinuxcn/ciyue/lilac.yaml
archlinuxcn/danxi-git/lilac.yaml
archlinuxcn/danxi/lilac.yaml
archlinuxcn/kazumi/lilac.yaml
archlinuxcn/piliplus/lilac.yaml

Remove fvm from `repo_makedepends` as fvm is now available in [the official repository](https://archlinux.org/packages/extra/x86_64/fvm).

Remove fvm from `repo_makedepends` to use extra/fvm

---

archlinuxcn/maa-assistant-arknights/PKGBUILD

NVCC dropped support for old arch recently

maa-assistant-arknights: fix cuda build

---

archlinuxcn/rustnet/PKGBUILD
archlinuxcn/rustnet/lilac.yaml
archlinuxcn/rustnet/rustnet-setcap.hook
archlinuxcn/rustnet/rustnet.install

[RustNet](https://github.com/domcyrus/rustnet)仓库目前共有1.2k个star，且采用Apache-2.0许可证，我想应该有资格被加入这个仓库吧。
AUR上虽然有[rustnet-bin](https://aur.archlinux.org/packages/rustnet-bin)，但其依赖`libpcap.so.0.8`。目前该包的方法是创建软链接。不过我觉得可能不太好，因此还是选择直接从源代码构建。
本地构建看起来没有问题，不过会出现警告：`软件包含有对 $srcdir 的引用`，我不知道如何消除🤣。
<details>
<summary>
使用`namcap`的检查结果
</summary>
```bash
PKGBUILD (rustnet) I: Missing Contributor tag
rustnet I: Soname 'libgcc_s.so=1-64' is not specified as provides by gcc-libs yet (needed in files ['usr/bin/rustnet'])
rustnet I: Soname 'ld-linux-x86-64.so=2-64' is not specified as provides by glibc yet (needed in files ['usr/bin/rustnet'])
rustnet I: Soname 'libc.so=6-64' is not specified as provides by glibc yet (needed in files ['usr/bin/rustnet'])
rustnet I: Soname 'libm.so=6-64' is not specified as provides …
```

addpkg: rustnet

---

archlinuxcn/rustnet/PKGBUILD
archlinuxcn/rustnet/lilac.yaml
archlinuxcn/v2ray-rules-dat/PKGBUILD
archlinuxcn/v2ray-rules-dat/lilac.yaml

- Add maintainer and contributor to reflect the current situation.
- Change my email address to `archlinuxcn.org`.

chore: Update email addresses and add maintainer
